{
  "module": {
    "name": "CalculateDistanceToField",
    "namespace": "Fields",
    "status": "Real ported module",
    "description": "...",
    "header": "Modules/Legacy/Fields/CalculateDistanceToField.h"
  },
  "algorithm": {
    "name": "CalculateDistanceFieldAlgo",
    "namespace": "Fields",
    "header": "Core/Algorithms/Legacy/Fields/DistanceField/CalculateDistanceField.h"
  },
  "UI": {
    "name": "N/A",
    "header": "N/A"
  }
}
