{
  "module": {
    "name": "CalculateSignedDistanceToField",
    "namespace": "Fields",
    "status": "Second real ported module",
    "description": "...",
    "header": "Modules/Legacy/Fields/CalculateSignedDistanceToField.h"
  },
  "algorithm": {
    "name": "CalculateSignedDistanceFieldAlgo",
    "namespace": "Fields",
    "header": "Core/Algorithms/Legacy/Fields/DistanceField/CalculateSignedDistanceField.h"
  },
  "UI": {
    "name": "N/A",
    "header": "N/A"
  }
}
