{
  "module": {
    "name": "CompositeModuleWithTypedStaticPorts",
    "namespace": "Basic",
    "status": "...",
    "description": "...",
    "header": "Modules/Basic/CompositeModuleWithTypedStaticPorts.h"
  },
  "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "CompositeModuleDialog",
    "header": "Interface/Modules/Python/CompositeModuleDialog.h"
  }
}
