{
  "module": {
    "name": "ConditionalMatrix",
    "namespace": "Math",
    "status": “new module“,
    "description": “compare matrices and send output accordingly”,
    "header": "Modules/Math/ConditionalMatrix.h"
  },
  "algorithm": {
    "name": "ConditionalMatrixAlgo”,
    "namespace": “Math”,
    "header": “Core/Algorithms/Math/ConditionalMatrixAlgo.h“
  },
  "UI": {
    "name": "ConditionalMatrixDialog",
    "header": "Interface/Modules/Math/ConditionalMatrixDialog.h"
  }
}
