{
  "module": {
    "name": "ConvertMatricesToMesh",
    "namespace": "Fields",
    "status": "Ported module",
    "description": "Store/retrieve values from an input matrix to/from the data of a field",
    "header": "Modules/Legacy/Fields/ConvertMatricesToMesh.h"
  },
  "algorithm": {
    "name": "ConvertMatricesToMeshAlgo",
    "namespace": "Fields",
    "header": "Core/Algorithms/Legacy/Fields/CreateMesh/ConvertMatricesToMeshAlgo.h"
  },
  "UI": {
    "name": "ConvertMatricesToMeshDialog",
    "header": "Interface/Modules/Fields/ConvertMatricesToMeshDialog.h"
  }
}
