{
  "module": {
    "name": "ConvertRealToComplexMatrix",
    "namespace": "Math",
    "status": "New module.  Needs testing.",
    "description": "Converts two real-valued to a complex-valued matrix",
    "header": "Modules/Math/ConvertRealToComplexMatrix.h"
  },
  "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "N/A",
    "header": "N/A"
  }
}
