{
  "module": {
    "name": "CreateLatVol",
    "namespace": "Fields",
    "status": "Ported module",
    "description": "Creates Lattice Volumes",
    "header": "Modules/Legacy/Fields/CreateLatVol.h"
  },
  "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "CreateLatVolDialog",
    "header": "Interface/Modules/Fields/CreateLatVolDialog.h"
  }
}
