{
  "module": {
    "name": "ExportFieldsToMatlab",
    "namespace": "Matlab",
    "status": "Ported module",
    "description": "TODO",
    "header": "Modules/Legacy/Matlab/DataIO/ExportFieldsToMatlab.h"
  },
  "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "ExportFieldsToMatlabDialog",
    "header": "Interface/Modules/Matlab/ExportFieldsToMatlabDialog.h"
  }
}
