{
  "module": {
    "name": "GenerateElectrode",
    "namespace": "Fields",
    "status": "Ported module: no UI yet",
    "description": "Makes a wire geom with interactive widgets",
    "header": "Modules/Legacy/Fields/GenerateElectrode.h"
  },
  "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "GenerateElectrodeDialog",
    "header": "Interface/Modules/Fields/GenerateElectrodeDialog.h"
  }
}
