{
  "module": {
    "name": "GenerateStandardMatrix",
    "namespace": "Math",
    "status": "new module",
    "description": "Generates Several different Types of Standard Matrices",
    "header": "Modules/Math/GenerateStandardMatrix.h"
  },
  "algorithm": {
    "name": "GenerateStandardMatrixAlgo",
    "namespace": "Math",
    "header": "Core/Algorithms/Math/GenerateStandardMatrixAlgo.h"
  },
  "UI": {
    "name": "GenerateStandardMatrixDialog",
    "header": "Interface/Modules/Math/GenerateStandardMatrixDialog.h"
  }
}
