{
  "module": {
    "name": "GeometryBuffer",
    "namespace": "Visualization",
    "status": "in progress--needs testing",
    "description": "...",
    "header": "Modules/Visualization/GeometryBuffer.h"
  },
  "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "GeometryBufferDialog",
    "header": "Interface/Modules/Visualization/GeometryBufferDialog.h"
  }
}
