{
  "module": {
    "name": "GetColorMapInfo",
    "namespace": "Visualization",
    "status": " Module working with ui.  No algorithm file.",
    "description": "This module allows for the extraction of strings from bundle files.",
    "header": "Modules/Visualization/GetColorMapInfo.h"
  },
  "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "GetColorMapInfoDialog",
    "header": "Interface/Modules/Visualization/GetColorMapInfoDialog.h"
  }
}
