{
  "module": {
    "name": "GetMatricesFromBundle",
    "namespace": "Bundles",
    "status": "Converted",
    "description": "Retrieves a matrix object from a bundle",
    "header": "Modules/Legacy/Bundle/GetMatricesFromBundle.h"
  },
  "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "GetMatricesFromBundleDialog",
    "header": "Interface/Modules/Bundle/GetMatricesFromBundleDialog.h"
  }
}
