{
  "module": {
    "name": "GetStringsFromBundle",
    "namespace": "Bundles",
    "status": " Module working with ui.  No algorithm file.",
    "description": "This module allows for the extraction of strings from bundle files.",
    "header": "Modules/Legacy/Bundle/GetStringsFromBundle.h"
  },
  "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "GetStringsFromBundleDialog",
    "header": "Interface/Modules/Bundle/GetStringsFromBundleDialog.h"
  }
}
