{
  "module": {
    "name": "GetStringsFromBundle",
    "namespace": "Bundle",
    "status": " No algorithm.",
    "description": "This module allows for the extraction of strings from bundle files.",
    "header": "Modules/Legacy/String/GetStringsFromBundle.h"
  },
  "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "GetStringsFromBundleDialog",
    "header": "Interface/Modules/Buundle/GetStringsFromBundleDialog.h"
  }
}
