{
"module":
    {
    "name": "GravitySimulation",
    "namespace": "ParticleInCell",
    "status": "new module",
    "description": "This module in ParticleInCell has a UI and Algorithm",
    "header": "Modules/ParticleInCell/GravitySimulation.h"
     },

"algorithm":
    {
    "name": "GravitySimulationAlgo",
    "namespace": "ParticleInCell",
    "header": "Core/Algorithms/ParticleInCell/GravitySimulationAlgo.h"
    },

"UI":
    {
    "name": "GravitySimulationDialog",
    "header": "Interface/Modules/ParticleInCell/GravitySimulationDialog.h"
    }
}
