{
"module":
    {
    "name": "GravitySim",
    "namespace": "ParticleInCell",
    "status": "new module",
    "description": "The P1_GravitySim program",
    "header": "Modules/ParticleInCell/GravitySim.h"
     },

"algorithm":
    {
    "name": "GravitySimAlgo",
    "namespace": "ParticleInCell",
    "header": "Core/Algorithms/ParticleInCell/GravitySimAlgo.h"
    },

"UI":
    {
    "name": "N/A",
    "header": "N/A"
    }
}
