{
  "module": {
    "name": "InterfaceWithPython",
    "namespace": "Python",
    "status": "In progress",
    "description": "TODO",
    "header": "Modules/Python/InterfaceWithPython.h"
  },
  "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "InterfaceWithPythonDialog",
    "header": "Interface/Modules/Python/InterfaceWithPythonDialog.h"
  }
}
