{
  "module": {
    "name": "InterfaceWithOspray",
    "namespace": "Visualization",
    "status": "...",
    "description": "...",
    "header": "Modules/Visualization/InterfaceWithOspray.h"
  },
  "algorithm": {
    "name": "OsprayDataAlgorithm",
    "namespace": "Visualization",
    "header": "Core/Algorithms/Visualization/OsprayAlgorithm.h"
  },
  "UI": {
    "name": "InterfaceWithOsprayDialog",
    "header": "Interface/Modules/Visualization/InterfaceWithOsprayDialog.h"
  }
}
