{
  "module": {
    "name": "ModelTMSCoilSingle",
    "namespace": "BrainStimulator",
    "status": "converted based on code from Petar Petrov",
    "description": "Creates geometry of a single coil",
    "header": "Modules/BrainStimulator/ModelTMSCoilSingle.h"
  },
  "algorithm": {
    "name": "ModelTMSCoilSingleAlgorithm",
    "namespace": "BrainStimulator",
    "header": "Core/Algorithms/BrainStimulator/ModelGenericCoilAlgorithm.h"
  },
  "UI": {
    "name": "ModelTMSCoilSingleDialog",
    "header": "Interface/Modules/BrainStimulator/ModelTMSCoilSingleDialog.h"
  }
}
