{
  "module": {
    "name": "ModelTMSCoilDipole",
    "namespace": "BrainStimulator",
    "status": "converted based on code from Petar Petrov",
    "description": "Creates geometry of a Dipole coil",
    "header": "Modules/BrainStimulator/ModelTMSCoilDipole.h"
  },
  "algorithm": {
    "name": "ModelTMSCoilDipoleAlgorithm",
    "namespace": "BrainStimulator",
    "header": "Core/Algorithms/BrainStimulator/ModelGenericCoilAlgorithm.h"
  },
  "UI": {
    "name": "ModelTMSCoilDipoleDialog",
    "header": "Interface/Modules/BrainStimulator/ModelTMSCoilDipoleDialog.h"
  }
}
