{
"module":
    {
    "name": "ModuleShell",
    "namespace": "ParticleInCell",
    "status": "new module",
    "description": "Base Particle In Cell simulation module",
    "header": "Modules/ParticleInCell/ModuleShell.h"
     },

"algorithm":
    {
    "name": "ModuleShellAlgo",
    "namespace": "ParticleInCell",
    "header": "Core/Algorithms/ParticleInCell/ModuleShellAlgo.h"
    },

"UI":
    {
    "name": "N/A",
    "header": "N/A"
    }
}
