{
"module":
    {
    "name": "PIConGPUReader",
    "namespace": "ParticleInCell",
    "status": "new module",
    "description": "PIConGPU openPMD Reader module",
    "header": "Modules/ParticleInCell/PIConGPUReader.h"
    },

"algorithm":
    {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
    },

"UI":
    {
    "name": "PIConGPUReaderDialog",
    "header": "Interface/Modules/ParticleInCell/PIConGPUReaderDialog.h"
    }
}
