{
  "module": {
    "name": "PlaceholderModule",
    "namespace": "Basic",
    "status": "Placeholder for missing v4 modules",
    "description": "Errors every time",
    "header": "Modules/Basic/PlaceholderModule.h"
  },
  "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "PlaceholderModuleDialog",
    "header": "Interface/Modules/String/PlaceholderModuleDialog.h"
  }
}
