{
  "module": {
    "name": "RefineTetMeshLocally",
    "namespace": "Fields",
    "status": "...",
    "description": "...",
    "header": "Modules/Fields/RefineTetMeshLocally.h"
  },
  "algorithm": {
    "name": "RefineTetMeshLocallyAlgorithm",
    "namespace": "Fields",
    "header": "Core/Algorithms/Field/RefineTetMeshLocallyAlgorithm.h"
  },
  "UI": {
    "name": "RefineTetMeshLocallyDialog",
    "header": "Interface/Modules/Fields/RefineTetMeshLocallyDialog.h"
  }
}
