{
  "module": {
    "name": "ReorderNormalCoherently",
    "namespace": "Fields",
    "status": "new module",
    "description": "reorders the normals so they are all facing the same direction",
    "header": "Modules/Legacy/Fields/ReorderNormalCoherently.h"
  },
  "algorithm": {
    "name": "ReorderNormalCoherentlyAlgo",
    "namespace": "Fields",
    "header": "Core/Algorithms/Legacy/Fields/Cleanup/ReorderNormalCoherentlyAlgo.h"
  },
  "UI": {
    "name": "ReorderNormalCoherentlyDialog",
    "header": "Interface/Modules/Fields/ReorderNormalCoherentlyDialog.h"
  }
}
