{
  "module": {
    "name": "ReportBundleInfo",
    "namespace": "Bundles",
    "status": "Ported module",
    "description": "...",
    "header": "Modules/Legacy/Bundle/ReportBundleInfo.h"
  },
  "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "ReportBundleInfoDialog",
    "header": "Interface/Modules/Bundle/ReportBundleInfoDialog.h"
  }
}
