{
  "module": {
    "name": "ReportColumnMatrixMisfit",
    "namespace": "Math",
    "status": "Real ported module: GUI incomplete, untested",
    "description": "...",
    "header": "Modules/Legacy/Math/ReportColumnMatrixMisfit.h"
  },
  "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "ReportColumnMatrixMisfitDialog",
    "header": "Interface/Modules/Math/ReportColumnMatrixMisfitDialog.h"
  }
}
