{
  "module": {
    "name": "ReportScalarFieldStats",
    "namespace": "Fields",
    "status": "Converted",
    "description": "...",
    "header": "Modules/Legacy/Fields/ReportScalarFieldStats.h"
  },
  "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "ReportScalarFieldStatsDialog",
    "header": "Interface/Modules/Fields/ReportScalarFieldStatsDialog.h"
  }
}
