{
  "module": {
    "name": "ReportFieldGeometryMeasures",
    "namespace": "Fields",
    "status": "Converted",
    "description": "TODO",
    "header": "Modules/Legacy/Fields/ReportFieldGeometryMeasures.h"
  },
  "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "ReportFieldGeometryMeasuresDialog",
    "header": "Interface/Modules/Fields/ReportFieldGeometryMeasuresDialog.h"
  }
}
