{
  "module": {
    "name": "ShowString",
    "namespace": "Visualization",
    "status": "in progress--needs testing",
    "description": "...",
    "header": "Modules/Visualization/ShowString.h"
  },
  "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "ShowStringDialog",
    "header": "Interface/Modules/Visualization/ShowStringDialog.h"
  }
}
