{
  "module": {
    "name": "ShowOrientationAxes",
    "namespace": "Visualization",
    "status": "...",
    "description": "",
    "header": "Modules/Visualization/ShowOrientationAxes.h"
  },
  "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "ShowOrientationAxesDialog",
    "header": "Interface/Modules/Visualization/ShowOrientationAxesDialog.h"
  }
}
