{
  "module": {
    "name": "ShowAndEditDipoles",
    "namespace": "Visualization",
    "status": "...",
    "description": "...",
    "header": "Modules/Legacy/Visualization/ShowAndEditDipoles.h"
  },
   "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "ShowAndEditDipolesDialog",
    "header": "Interface/Modules/Visualization/ShowAndEditDipolesDialog.h"
  }
}
