{
  "module": {
    "name": "ShowColorMap",
    "namespace": "Visualization",
    "status": "Real ported module",
    "description": "...",
    "header": "Modules/Visualization/ShowColorMapModule.h"
  },
  "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "ShowColorMapDialog",
    "header": "Interface/Modules/Visualization/ShowColorMapDialog.h"
  }
}
