{
  "module": {
    "name": "ShowFieldGlyphs",
    "namespace": "Visualization",
    "status": "Rewrite",
    "description": "...",
    "header": "Modules/Visualization/ShowFieldGlyphs.h"
  },
  "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "ShowFieldGlyphsDialog",
    "header": "Interface/Modules/Visualization/ShowFieldGlyphsDialog.h"
  }
}
