{
  "module": {
    "name": "ShowUncertaintyGlyphs",
    "namespace": "Visualization",
    "status": "...",
    "description": "...",
    "header": "Modules/Visualization/ShowUncertaintyGlyphs.h"
  },
  "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "ShowUncertaintyGlyphsDialog",
    "header": "Interface/Modules/Visualization/ShowUncertaintyGlyphsDialog.h"
  }
}
