{
  "module": {
    "name": "SolveInverseProblemWithTikhonovTSVD",
    "namespace": "Inverse",
    "status": "Ported module",
    "description": "...",
    "header": "Modules/Legacy/Inverse/SolveInverseProblemWithTikhonovTSVD.h"
  },
  "algorithm": {
    "name": "TikhonovAlgoAbstractBase",
    "namespace": "Inverse",
    "header": "Core/Algorithms/Legacy/Inverse/TikhonovAlgoAbstractBase.h"
  },
  "UI": {
    "name": "SolveInverseProblemWithTikhonovTSVDDialog",
    "header": "Interface/Modules/Inverse/SolveInverseProblemWithTikhonovTSVDDialog.h"
  }
}
