{
"module":
    {
    "name": "SortMatrix",
    "namespace": "ParticleInCell",
    "status": "new module",
    "description": "This is the Tutorial SortMatrix module imolemented in ParticleInCell",
    "header": "Modules/ParticleInCell/SortMatrix.h"
     },

"algorithm":
    {
    "name": "SortMatrixAlgo",
    "namespace": "ParticleInCell",
    "header": "Core/Algorithms/ParticleInCell/SortMatrixAlgo.h"
    },

"UI":
    {
    "name": "SortMatrixDialog",
    "header": "Interface/Modules/ParticleInCell/SortMatrixDialog.h"
    }
}
