{
  "module": {
    "name": "SplitFieldByDomain",
    "namespace": "Fields",
    "status": "Ported module",
    "description": "...",
    "header": "Modules/Legacy/Fields/SplitFieldByDomain.h"
  },
  "algorithm": {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
  },
  "UI": {
    "name": "SplitFieldByDomainDialog",
    "header": "Interface/Modules/Fields/SplitFieldByDomainDialog.h"
  }
}
