{
  "module": {
    "name": "TransformMeshWithTransform",
    "namespace": "Fields",
    "status": "...",
    "description": "...",
    "header": "Modules/Legacy/Fields/TransformMeshWithTransform.h"
  },
  "algorithm": {
    "name": "TransformMeshWithTransformAlgo",
    "namespace": "Fields",
    "header": "Core/Algorithms/Legacy/Fields/TransformMesh/TransformMeshWithTransform.h"
  },
  "UI": {
    "name": "N/A",
    "header": "N/A"
  }
}
