version: '{build}'
branches:
  only:
  - windows-build-experimental
clone_folder: c:\scirun
image:
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
environment:
  matrix:
  - arch: Win64
  # - arch: #does not work, Release|x64 not a valid target
matrix:
  fast_finish: true

# skip unsupported combinations
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- echo %generator%

before_build:
- cmd: |-
    cd bin
    cmake --version
    cmake ..\Superbuild -G %generator% -DQt5_PATH:PATH="C:\Qt\5.14.1\msvc2017_64" -DBUILD_WITH_PYTHON:BOOL=OFF -DTRAVIS_BUILD:BOOL=ON

build:
  project: c:\scirun\bin\Superbuild.sln
  verbosity: minimal
  parallel: true
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - src/
    - Superbuild/
