{
"module":
    {
    "name": "PIConGPUReaderAsynch",
    "namespace": "ParticleInCell",
    "status": "new module",
    "description": "An asynchronous PIConGPU openPMD Reader module",
    "header": "Modules/ParticleInCell/PIConGPUReaderAsynch.h"
     },

"algorithm":
    {
    "name": "N/A",
    "namespace": "N/A",
    "header": "N/A"
    },

"UI":
    {
    "name": "PIConGPUReaderAsynchDialog",
    "header": "Interface/Modules/ParticleInCell/PIConGPUReaderAsynchDialog.h"
    }
}
