# SCIRun network exported to Python.
# Run it with `scirun -s <this file>`, or paste it into the SCIRun Python console.
# Module IDs are reassigned when the script runs, so modules are referred to by variable.

skipped = []
def set_state(module, key, value):
    # Saved networks can hold keys or value types that this version's modules no longer accept.
    try:
        scirun_set_module_state(module, key, value)
    except (ValueError, RuntimeError) as e:
        skipped.append(f"{module} {key}: {e}")

appendMatrix_0 = scirun_add_module("AppendMatrix")
buildFEMatrix_0 = scirun_add_module("BuildFEMatrix")
calculateFieldData_0 = scirun_add_module("CalculateFieldData")
createStandardColorMap_0 = scirun_add_module("CreateStandardColorMap")
evaluateLinearAlgebraUnary_0 = scirun_add_module("EvaluateLinearAlgebraUnary")
evaluateLinearAlgebraUnary_1 = scirun_add_module("EvaluateLinearAlgebraUnary")
getFieldNodes_0 = scirun_add_module("GetFieldNodes")
getFieldNodes_2 = scirun_add_module("GetFieldNodes")
mapFieldDataFromSourceToDestination_0 = scirun_add_module("MapFieldDataFromSourceToDestination")
readField_0 = scirun_add_module("ReadField")
readField_10 = scirun_add_module("ReadField")
readField_9 = scirun_add_module("ReadField")
reportMatrixInfo_1 = scirun_add_module("ReportMatrixInfo")
rescaleColorMap_0 = scirun_add_module("RescaleColorMap")
selectSubMatrix_0 = scirun_add_module("SelectSubMatrix")
setConductivitiesToMesh_0 = scirun_add_module("SetConductivitiesToMesh")
setFieldData_0 = scirun_add_module("SetFieldData")
setFieldNodes_0 = scirun_add_module("SetFieldNodes")
setupTDCS_0 = scirun_add_module("SetupTDCS")
showField_0 = scirun_add_module("ShowField")
solveLinearSystem_0 = scirun_add_module("SolveLinearSystem")
viewScene_1 = scirun_add_module("ViewScene")

# AppendMatrix:0
set_state(appendMatrix_0, "ProgrammableInputPortEnabled", False)
set_state(appendMatrix_0, "RowsOrColumns", 1)

# BuildFEMatrix:0
set_state(buildFEMatrix_0, "ProgrammableInputPortEnabled", False)

# CalculateFieldData:0
set_state(calculateFieldData_0, "FormatString", "Scalar")
set_state(calculateFieldData_0, "FunctionString", "RESULT = select(DATA1==1,1,select(DATA1==2,2,select(DATA1==3, 4,select(DATA1==4,6,select(DATA1==5,5,NAN)))));")
set_state(calculateFieldData_0, "ProgrammableInputPortEnabled", False)

# CreateStandardColorMap:0
set_state(createStandardColorMap_0, "AlphaUserPointsVector", [])
set_state(createStandardColorMap_0, "ColorMapInvert", False)
set_state(createStandardColorMap_0, "ColorMapName", "Rainbow")
set_state(createStandardColorMap_0, "ColorMapOption", 0)
set_state(createStandardColorMap_0, "ColorMapResolution", 256)
set_state(createStandardColorMap_0, "ColorMapShift", 0.0)
set_state(createStandardColorMap_0, "CustomColor0", "Color(0.2,0.2,0.2)")
set_state(createStandardColorMap_0, "CustomColor1", "Color(0.8,0.8,0.8)")
set_state(createStandardColorMap_0, "DefaultAlphaValue", 0.5)
set_state(createStandardColorMap_0, "ProgrammableInputPortEnabled", False)

# EvaluateLinearAlgebraUnary:0
set_state(evaluateLinearAlgebraUnary_0, "FunctionString", "x+10")
set_state(evaluateLinearAlgebraUnary_0, "Operator", 2)
set_state(evaluateLinearAlgebraUnary_0, "ProgrammableInputPortEnabled", False)
set_state(evaluateLinearAlgebraUnary_0, "ScalarValue", 0.001)

# EvaluateLinearAlgebraUnary:1
set_state(evaluateLinearAlgebraUnary_1, "FunctionString", "x*0+1")
set_state(evaluateLinearAlgebraUnary_1, "Operator", 3)
set_state(evaluateLinearAlgebraUnary_1, "ProgrammableInputPortEnabled", False)
set_state(evaluateLinearAlgebraUnary_1, "ScalarValue", 0)

# GetFieldNodes:0
set_state(getFieldNodes_0, "ProgrammableInputPortEnabled", False)

# GetFieldNodes:2
set_state(getFieldNodes_2, "ProgrammableInputPortEnabled", False)

# MapFieldDataFromSourceToDestination:0
set_state(mapFieldDataFromSourceToDestination_0, "DefaultValue", 0.0)
set_state(mapFieldDataFromSourceToDestination_0, "MappingMethod", "interpolateddata")
set_state(mapFieldDataFromSourceToDestination_0, "MaxDistance", -1.0)
set_state(mapFieldDataFromSourceToDestination_0, "ProgrammableInputPortEnabled", False)

# ReadField:0
set_state(readField_0, "FileTypeName", "Matlab Field")
set_state(readField_0, "Filename", "%SCIRUNDATADIR%/IBBM2015/BrainStimulator/mesh.mat")
set_state(readField_0, "GuiFileTypeName", "")
set_state(readField_0, "ProgrammableInputPortEnabled", False)
set_state(readField_0, "ScriptEnvironmentVariable", "")

# ReadField:10
set_state(readField_10, "FileTypeName", "Matlab Field")
set_state(readField_10, "Filename", "%SCIRUNDATADIR%/IBBM2015/BrainStimulator/elc_nodes.mat")
set_state(readField_10, "GuiFileTypeName", "")
set_state(readField_10, "ProgrammableInputPortEnabled", False)
set_state(readField_10, "ScriptEnvironmentVariable", "")

# ReadField:9
set_state(readField_9, "FileTypeName", "Matlab Field")
set_state(readField_9, "Filename", "%SCIRUNDATADIR%/IBBM2015/BrainStimulator/scalp.mat")
set_state(readField_9, "GuiFileTypeName", "")
set_state(readField_9, "ProgrammableInputPortEnabled", False)
set_state(readField_9, "ScriptEnvironmentVariable", "")

# ReportMatrixInfo:1
set_state(reportMatrixInfo_1, "ProgrammableInputPortEnabled", False)

# RescaleColorMap:0
set_state(rescaleColorMap_0, "AutoScale", 0)
set_state(rescaleColorMap_0, "FixedMax", 0.1524445444651314)
set_state(rescaleColorMap_0, "FixedMin", -0.16010933815815212)
set_state(rescaleColorMap_0, "ProgrammableInputPortEnabled", False)
set_state(rescaleColorMap_0, "Symmetric", False)

# SelectSubMatrix:0
set_state(selectSubMatrix_0, "ProgrammableInputPortEnabled", False)
set_state(selectSubMatrix_0, "columnCheckBox", True)
set_state(selectSubMatrix_0, "columnEndSpinBox", 0)
set_state(selectSubMatrix_0, "columnStartSpinBox", 0)
set_state(selectSubMatrix_0, "rowCheckBox", False)
set_state(selectSubMatrix_0, "rowEndSpinBox", 0)
set_state(selectSubMatrix_0, "rowStartSpinBox", 0)

# SetConductivitiesToMesh:0
set_state(setConductivitiesToMesh_0, "CSF", 1.79)
set_state(setConductivitiesToMesh_0, "Electrode", 0.0)
set_state(setConductivitiesToMesh_0, "GM", 0.33)
set_state(setConductivitiesToMesh_0, "HardBone", 0.0)
set_state(setConductivitiesToMesh_0, "InternalAir", 0.0)
set_state(setConductivitiesToMesh_0, "ProgrammableInputPortEnabled", False)
set_state(setConductivitiesToMesh_0, "Skin", 0.43)
set_state(setConductivitiesToMesh_0, "SoftBone", 0.01)
set_state(setConductivitiesToMesh_0, "WM", 0.142)

# SetFieldData:0
set_state(setFieldData_0, "ProgrammableInputPortEnabled", False)
set_state(setFieldData_0, "keepTypeCheckBox", False)

# SetFieldNodes:0
set_state(setFieldNodes_0, "ProgrammableInputPortEnabled", False)

# SetupTDCS:0
set_state(setupTDCS_0, "ElectrodeTableValues", [1.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
set_state(setupTDCS_0, "GetContactSurface", False)
set_state(setupTDCS_0, "ImpedanceTableValues", [5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0, 5000.0])
set_state(setupTDCS_0, "ProgrammableInputPortEnabled", False)
set_state(setupTDCS_0, "SurfaceAreaValues", ["NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN"])
set_state(setupTDCS_0, "normal_dot_product_bound", 0.7)
set_state(setupTDCS_0, "number_of_electrodes", 78)
set_state(setupTDCS_0, "pointdistancebound", 0.001)
set_state(setupTDCS_0, "refnode", 0)

# ShowField:0
set_state(showField_0, "CullBackfacingText", False)
set_state(showField_0, "CylinderRadius", 0.1)
set_state(showField_0, "CylinderResolution", 5)
set_state(showField_0, "DefaultMeshColor", "Color(0.5,0.5,0.5)")
set_state(showField_0, "DefaultTextColor", "Color(1,1,1)")
set_state(showField_0, "EdgeTransparency", False)
set_state(showField_0, "EdgeTransparencyValue", 0.6499999761581421)
set_state(showField_0, "EdgesAsCylinders", 0)
set_state(showField_0, "EdgesAvailable", True)
set_state(showField_0, "EdgesColoring", 1)
set_state(showField_0, "FaceInvertNormals", False)
set_state(showField_0, "FaceTransparency", False)
set_state(showField_0, "FaceTransparencyValue", 0.6499999761581421)
set_state(showField_0, "FacesAvailable", True)
set_state(showField_0, "FacesColoring", 1)
set_state(showField_0, "FieldName", "")
set_state(showField_0, "NodeAsSpheres", 0)
set_state(showField_0, "NodeTransparency", False)
set_state(showField_0, "NodeTransparencyValue", 0.6499999761581421)
set_state(showField_0, "NodesAvailable", True)
set_state(showField_0, "NodesColoring", 1)
set_state(showField_0, "ProgrammableInputPortEnabled", False)
set_state(showField_0, "RenderAsLocation", False)
set_state(showField_0, "ShowCellIndices", False)
set_state(showField_0, "ShowDataValues", True)
set_state(showField_0, "ShowEdgeIndices", False)
set_state(showField_0, "ShowEdges", False)
set_state(showField_0, "ShowFaceIndices", False)
set_state(showField_0, "ShowFaces", True)
set_state(showField_0, "ShowNodeIndices", False)
set_state(showField_0, "ShowNodes", False)
set_state(showField_0, "ShowText", False)
set_state(showField_0, "SphereResolution", 5)
set_state(showField_0, "SphereScaleValue", 0.03)
set_state(showField_0, "TextAlwaysVisible", False)
set_state(showField_0, "TextColoring", 0)
set_state(showField_0, "TextPrecision", 3)
set_state(showField_0, "TextSize", 8)
set_state(showField_0, "UseFaceNormals", False)

# SolveLinearSystem:0
set_state(solveLinearSystem_0, "MaxIterations", 1000)
set_state(solveLinearSystem_0, "Method", "minres")
set_state(solveLinearSystem_0, "Preconditioner", "Jacobi")
set_state(solveLinearSystem_0, "ProgrammableInputPortEnabled", False)
set_state(solveLinearSystem_0, "TargetError", 1e-05)

# ViewScene:1
set_state(viewScene_1, "Ambient", 0.2)
set_state(viewScene_1, "AxesSize", 10)
set_state(viewScene_1, "AxesVisible", True)
set_state(viewScene_1, "AxesX", 100)
set_state(viewScene_1, "AxesY", 100)
set_state(viewScene_1, "BackgroundColor", "Color(0,0,0)")
set_state(viewScene_1, "CameraDistance", 3.0)
set_state(viewScene_1, "CameraDistanceMinimum", 1e-10)
set_state(viewScene_1, "CameraLookAt", [0.0, 0.0, 0.0])
set_state(viewScene_1, "CameraRotation", [1.0, 0.0, 0.0, 0.0])
set_state(viewScene_1, "ClippingPlaneD", [0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
set_state(viewScene_1, "ClippingPlaneEnabled", [False, False, False, False, False, False])
set_state(viewScene_1, "ClippingPlaneNormalReversed", [False, False, False, False, False, False])
set_state(viewScene_1, "ClippingPlaneX", [0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
set_state(viewScene_1, "ClippingPlaneY", [0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
set_state(viewScene_1, "ClippingPlaneZ", [0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
set_state(viewScene_1, "Diffuse", 1.0)
set_state(viewScene_1, "Emission", 0.0)
set_state(viewScene_1, "FogColor", "Color(0,0,1)")
set_state(viewScene_1, "FogEnd", 0.71)
set_state(viewScene_1, "FogOn", False)
set_state(viewScene_1, "FogStart", 0.0)
set_state(viewScene_1, "HasNewGeometry", False)
set_state(viewScene_1, "HeadLightAzimuth", 180)
set_state(viewScene_1, "HeadLightColor", "Color(1,1,1)")
set_state(viewScene_1, "HeadLightInclination", 90)
set_state(viewScene_1, "HeadLightOn", True)
set_state(viewScene_1, "IsExecuting", False)
set_state(viewScene_1, "IsFloating", True)
set_state(viewScene_1, "Light1Azimuth", 180)
set_state(viewScene_1, "Light1Color", "Color(1,1,1)")
set_state(viewScene_1, "Light1Inclination", 90)
set_state(viewScene_1, "Light1On", False)
set_state(viewScene_1, "Light2Azimuth", 180)
set_state(viewScene_1, "Light2Color", "Color(1,1,1)")
set_state(viewScene_1, "Light2Inclination", 90)
set_state(viewScene_1, "Light2On", False)
set_state(viewScene_1, "Light3Azimuth", 180)
set_state(viewScene_1, "Light3Color", "Color(1,1,1)")
set_state(viewScene_1, "Light3Inclination", 90)
set_state(viewScene_1, "Light3On", False)
set_state(viewScene_1, "ObjectsOnly", True)
set_state(viewScene_1, "ProgrammableInputPortEnabled", False)
set_state(viewScene_1, "ScaleBarFontSize", 8)
set_state(viewScene_1, "ScaleBarHeight", 1.0)
set_state(viewScene_1, "ScaleBarLength", 1.0)
set_state(viewScene_1, "ScaleBarLineColor", 1.0)
set_state(viewScene_1, "ScaleBarLineWidth", 1.0)
set_state(viewScene_1, "ScaleBarMultiplier", 1.0)
set_state(viewScene_1, "ScaleBarNumTicks", 11)
set_state(viewScene_1, "ScaleBarUnitValue", "mm")
set_state(viewScene_1, "ScreenshotDirectory", "")
set_state(viewScene_1, "Shine", 0.5)
set_state(viewScene_1, "ShowScaleBar", False)
set_state(viewScene_1, "ShowViewer", False)
set_state(viewScene_1, "Specular", 0.3)
set_state(viewScene_1, "ToolBarAdvancedPosition", 2)
set_state(viewScene_1, "ToolBarMainPosition", 4)
set_state(viewScene_1, "ToolBarRenderPosition", 1)
set_state(viewScene_1, "UseBGColor", True)
set_state(viewScene_1, "VisibleItemListState", [])
set_state(viewScene_1, "WindowPositionX", 200)
set_state(viewScene_1, "WindowPositionY", 200)
set_state(viewScene_1, "WindowSizeX", 450)
set_state(viewScene_1, "WindowSizeY", 450)

scirun_connect_modules(getFieldNodes_0, 0, appendMatrix_0, 0)
scirun_connect_modules(evaluateLinearAlgebraUnary_1, 0, appendMatrix_0, 1)
scirun_connect_modules(setFieldNodes_0, 0, buildFEMatrix_0, 0)
scirun_connect_modules(readField_0, 0, calculateFieldData_0, 0)
scirun_connect_modules(getFieldNodes_2, 0, evaluateLinearAlgebraUnary_0, 0)
scirun_connect_modules(selectSubMatrix_0, 0, evaluateLinearAlgebraUnary_1, 0)
scirun_connect_modules(readField_10, 0, getFieldNodes_0, 0)
scirun_connect_modules(setConductivitiesToMesh_0, 0, getFieldNodes_2, 0)
scirun_connect_modules(setFieldData_0, 0, mapFieldDataFromSourceToDestination_0, 0)
scirun_connect_modules(readField_9, 0, mapFieldDataFromSourceToDestination_0, 1)
scirun_connect_modules(appendMatrix_0, 0, reportMatrixInfo_1, 0)
scirun_connect_modules(createStandardColorMap_0, 0, rescaleColorMap_0, 0)
scirun_connect_modules(mapFieldDataFromSourceToDestination_0, 0, rescaleColorMap_0, 1)
scirun_connect_modules(getFieldNodes_0, 0, selectSubMatrix_0, 0)
scirun_connect_modules(calculateFieldData_0, 0, setConductivitiesToMesh_0, 0)
scirun_connect_modules(setConductivitiesToMesh_0, 0, setFieldData_0, 0)
scirun_connect_modules(solveLinearSystem_0, 0, setFieldData_0, 1)
scirun_connect_modules(setConductivitiesToMesh_0, 0, setFieldNodes_0, 0)
scirun_connect_modules(evaluateLinearAlgebraUnary_0, 0, setFieldNodes_0, 1)
scirun_connect_modules(setConductivitiesToMesh_0, 0, setupTDCS_0, 0)
scirun_connect_modules(readField_9, 0, setupTDCS_0, 1)
scirun_connect_modules(readField_10, 0, setupTDCS_0, 2)
scirun_connect_modules(appendMatrix_0, 0, setupTDCS_0, 3)
scirun_connect_modules(mapFieldDataFromSourceToDestination_0, 0, showField_0, 0)
scirun_connect_modules(rescaleColorMap_0, 0, showField_0, 1)
scirun_connect_modules(buildFEMatrix_0, 0, solveLinearSystem_0, 0)
scirun_connect_modules(setupTDCS_0, 5, solveLinearSystem_0, 1)
scirun_connect_modules(showField_0, 0, viewScene_1, 0)

if skipped:
    print("Saved state not applied:\n  " + "\n  ".join(skipped))
