# SCIRun network exported to Python.
# Run it with `scirun -s <this file>`, or paste it into the SCIRun Python console.
# Module IDs are reassigned when the script runs, so modules are referred to by variable.

skipped = []
def set_state(module, key, value):
    # Saved networks can hold keys or value types that this version's modules no longer accept.
    try:
        scirun_set_module_state(module, key, value)
    except (ValueError, RuntimeError) as e:
        skipped.append(f"{module} {key}: {e}")

applyFEMCurrentSource_0 = scirun_add_module("ApplyFEMCurrentSource")
buildFEMatrix_0 = scirun_add_module("BuildFEMatrix")
clipFieldByFunction_0 = scirun_add_module("ClipFieldByFunction")
convertHexVolToTetVol_0 = scirun_add_module("ConvertHexVolToTetVol")
createFieldData_0 = scirun_add_module("CreateFieldData")
createLatVol_0 = scirun_add_module("CreateLatVol")
createLatVol_1 = scirun_add_module("CreateLatVol")
createMatrix_0 = scirun_add_module("CreateMatrix")
createStandardColorMap_0 = scirun_add_module("CreateStandardColorMap")
createStandardColorMap_1 = scirun_add_module("CreateStandardColorMap")
fairMesh_0 = scirun_add_module("FairMesh")
generatePointSamplesFromFieldOrWidget_0 = scirun_add_module("GeneratePointSamplesFromFieldOrWidget")
generateSinglePointProbeFromField_0 = scirun_add_module("GenerateSinglePointProbeFromField")
generateStreamLines_0 = scirun_add_module("GenerateStreamLines")
getDomainBoundary_0 = scirun_add_module("GetDomainBoundary")
getFieldBoundary_0 = scirun_add_module("GetFieldBoundary")
mapFieldDataOntoElements_0 = scirun_add_module("MapFieldDataOntoElements")
mapFieldDataOntoNodes_0 = scirun_add_module("MapFieldDataOntoNodes")
mapFieldDataOntoNodes_1 = scirun_add_module("MapFieldDataOntoNodes")
readField_0 = scirun_add_module("ReadField")
rescaleColorMap_0 = scirun_add_module("RescaleColorMap")
rescaleColorMap_1 = scirun_add_module("RescaleColorMap")
setFieldData_0 = scirun_add_module("SetFieldData")
showField_0 = scirun_add_module("ShowField")
showField_1 = scirun_add_module("ShowField")
showFieldGlyphs_0 = scirun_add_module("ShowFieldGlyphs")
solveLinearSystem_0 = scirun_add_module("SolveLinearSystem")
viewScene_0 = scirun_add_module("ViewScene")
viewScene_2 = scirun_add_module("ViewScene")

# ApplyFEMCurrentSource:0
set_state(applyFEMCurrentSource_0, "ModelType", "dipole")
set_state(applyFEMCurrentSource_0, "ProgrammableInputPortEnabled", False)
set_state(applyFEMCurrentSource_0, "SinkNode", 1)
set_state(applyFEMCurrentSource_0, "SourceNode", 0)

# BuildFEMatrix:0
set_state(buildFEMatrix_0, "ProgrammableInputPortEnabled", False)

# ClipFieldByFunction:0
set_state(clipFieldByFunction_0, "ClipMethod", "Element Center")
set_state(clipFieldByFunction_0, "FunctionString", "DATA1 > 0;")
set_state(clipFieldByFunction_0, "ProgrammableInputPortEnabled", False)

# ConvertHexVolToTetVol:0
set_state(convertHexVolToTetVol_0, "ProgrammableInputPortEnabled", False)

# CreateFieldData:0
set_state(createFieldData_0, "BasisString", "Linear")
set_state(createFieldData_0, "FormatString", "Vector")
set_state(createFieldData_0, "FunctionString", "RESULT = vector(1,1,1);")
set_state(createFieldData_0, "ProgrammableInputPortEnabled", False)

# CreateLatVol:0
set_state(createLatVol_0, "DataAtLocation", 1)
set_state(createLatVol_0, "ElementSizeNormalized", 0)
set_state(createLatVol_0, "PadPercent", 0.0)
set_state(createLatVol_0, "ProgrammableInputPortEnabled", False)
set_state(createLatVol_0, "XSize", 50)
set_state(createLatVol_0, "YSize", 50)
set_state(createLatVol_0, "ZSize", 70)

# CreateLatVol:1
set_state(createLatVol_1, "DataAtLocation", 0)
set_state(createLatVol_1, "ElementSizeNormalized", 0)
set_state(createLatVol_1, "PadPercent", 0.0)
set_state(createLatVol_1, "ProgrammableInputPortEnabled", False)
set_state(createLatVol_1, "XSize", 16)
set_state(createLatVol_1, "YSize", 16)
set_state(createLatVol_1, "ZSize", 16)

# CreateMatrix:0
set_state(createMatrix_0, "ProgrammableInputPortEnabled", False)
set_state(createMatrix_0, "TextEntry", "0\n22\n.002\n.25\n.05\n.15\n.07\n.007\n.006\n.7\n.3\n.3")

# CreateStandardColorMap:0
set_state(createStandardColorMap_0, "AlphaUserPointsVector", [])
set_state(createStandardColorMap_0, "ColorMapInvert", False)
set_state(createStandardColorMap_0, "ColorMapName", "Rainbow")
set_state(createStandardColorMap_0, "ColorMapOption", 0)
set_state(createStandardColorMap_0, "ColorMapResolution", 256)
set_state(createStandardColorMap_0, "ColorMapShift", 0.0)
set_state(createStandardColorMap_0, "CustomColor0", "Color(0.2,0.2,0.2)")
set_state(createStandardColorMap_0, "CustomColor1", "Color(0.8,0.8,0.8)")
set_state(createStandardColorMap_0, "DefaultAlphaValue", 0.5)
set_state(createStandardColorMap_0, "ProgrammableInputPortEnabled", False)

# CreateStandardColorMap:1
set_state(createStandardColorMap_1, "AlphaUserPointsVector", [])
set_state(createStandardColorMap_1, "ColorMapInvert", False)
set_state(createStandardColorMap_1, "ColorMapName", "Blackbody")
set_state(createStandardColorMap_1, "ColorMapOption", 0)
set_state(createStandardColorMap_1, "ColorMapResolution", 256)
set_state(createStandardColorMap_1, "ColorMapShift", 0.0)
set_state(createStandardColorMap_1, "CustomColor0", "Color(0.2,0.2,0.2)")
set_state(createStandardColorMap_1, "CustomColor1", "Color(0.8,0.8,0.8)")
set_state(createStandardColorMap_1, "DefaultAlphaValue", 0.5)
set_state(createStandardColorMap_1, "ProgrammableInputPortEnabled", False)

# FairMesh:0
set_state(fairMesh_0, "FairMeshMethod", "fast")
set_state(fairMesh_0, "FilterCutoff", 0.1)
set_state(fairMesh_0, "Lambda", 0.6307)
set_state(fairMesh_0, "NumIterations", 50)
set_state(fairMesh_0, "ProgrammableInputPortEnabled", False)

# GeneratePointSamplesFromFieldOrWidget:0
set_state(generatePointSamplesFromFieldOrWidget_0, "ClampToNodes", True)
set_state(generatePointSamplesFromFieldOrWidget_0, "DistributionType", "uniscat")
set_state(generatePointSamplesFromFieldOrWidget_0, "IncrementRNGSeed", True)
set_state(generatePointSamplesFromFieldOrWidget_0, "NumSamples", 100)
set_state(generatePointSamplesFromFieldOrWidget_0, "ProgrammableInputPortEnabled", False)
set_state(generatePointSamplesFromFieldOrWidget_0, "RNGSeed", 5)

# GenerateSinglePointProbeFromField:0
set_state(generateSinglePointProbeFromField_0, "BBoxSize", 10.0)
set_state(generateSinglePointProbeFromField_0, "DisplayElem", True)
set_state(generateSinglePointProbeFromField_0, "DisplayNode", True)
set_state(generateSinglePointProbeFromField_0, "DisplayValue", True)
set_state(generateSinglePointProbeFromField_0, "FieldElem", 13469374)
set_state(generateSinglePointProbeFromField_0, "FieldNode", 5631534)
set_state(generateSinglePointProbeFromField_0, "FieldValue", "10")
set_state(generateSinglePointProbeFromField_0, "MoveMethod", "Location")
set_state(generateSinglePointProbeFromField_0, "ProbeColor", "Color(1,1,1)")
set_state(generateSinglePointProbeFromField_0, "ProbeLabel", "")
set_state(generateSinglePointProbeFromField_0, "ProbeSize", 0.5)
set_state(generateSinglePointProbeFromField_0, "ProgrammableInputPortEnabled", False)
set_state(generateSinglePointProbeFromField_0, "SnapToElement", False)
set_state(generateSinglePointProbeFromField_0, "SnapToNode", False)
set_state(generateSinglePointProbeFromField_0, "UseBBoxSize", False)
set_state(generateSinglePointProbeFromField_0, "XLocation", 0.0)
set_state(generateSinglePointProbeFromField_0, "YLocation", 0.0)
set_state(generateSinglePointProbeFromField_0, "ZLocation", 0.0)

# GenerateStreamLines:0
set_state(generateStreamLines_0, "AutoParameters", False)
set_state(generateStreamLines_0, "ProgrammableInputPortEnabled", False)
set_state(generateStreamLines_0, "RemoveColinearPoints", False)
set_state(generateStreamLines_0, "StreamlineDirection", "Both")
set_state(generateStreamLines_0, "StreamlineMaxSteps", 500)
set_state(generateStreamLines_0, "StreamlineMethod", "RungeKuttaFehlberg")
set_state(generateStreamLines_0, "StreamlineStepSize", 0.1)
set_state(generateStreamLines_0, "StreamlineTolerance", 0.001)
set_state(generateStreamLines_0, "StreamlineValue", "Seed index")
set_state(generateStreamLines_0, "UseMultithreading", True)

# GetDomainBoundary:0
set_state(getDomainBoundary_0, "AddOuterBoundary", True)
set_state(getDomainBoundary_0, "DisconnectBoundaries", False)
set_state(getDomainBoundary_0, "Domain", 1)
set_state(getDomainBoundary_0, "InnerBoundaryOnly", False)
set_state(getDomainBoundary_0, "MaxRange", 255)
set_state(getDomainBoundary_0, "MinRange", 10)
set_state(getDomainBoundary_0, "NoInnerBoundary", False)
set_state(getDomainBoundary_0, "ProgrammableInputPortEnabled", False)
set_state(getDomainBoundary_0, "UseRange", True)

# GetFieldBoundary:0
set_state(getFieldBoundary_0, "ProgrammableInputPortEnabled", False)

# MapFieldDataOntoElements:0
set_state(mapFieldDataOntoElements_0, "InterpolationModel", "interpolateddata")
set_state(mapFieldDataOntoElements_0, "MaxDistance", 1.7976931348623157e+308)
set_state(mapFieldDataOntoElements_0, "OutsideValue", 0.0)
set_state(mapFieldDataOntoElements_0, "ProgrammableInputPortEnabled", False)
set_state(mapFieldDataOntoElements_0, "Quantity", "value")
set_state(mapFieldDataOntoElements_0, "SampleMethod", "average")
set_state(mapFieldDataOntoElements_0, "SamplePoints", "regular1")

# MapFieldDataOntoNodes:0
set_state(mapFieldDataOntoNodes_0, "InterpolationModel", "interpolateddata")
set_state(mapFieldDataOntoNodes_0, "MaxDistance", 1.7976931348623157e+308)
set_state(mapFieldDataOntoNodes_0, "OutsideValue", 0.0)
set_state(mapFieldDataOntoNodes_0, "ProgrammableInputPortEnabled", False)
set_state(mapFieldDataOntoNodes_0, "Quantity", "gradient")

# MapFieldDataOntoNodes:1
set_state(mapFieldDataOntoNodes_1, "InterpolationModel", "interpolateddata")
set_state(mapFieldDataOntoNodes_1, "MaxDistance", 1.7976931348623157e+308)
set_state(mapFieldDataOntoNodes_1, "OutsideValue", 0.0)
set_state(mapFieldDataOntoNodes_1, "ProgrammableInputPortEnabled", False)
set_state(mapFieldDataOntoNodes_1, "Quantity", "gradientnorm")

# ReadField:0
set_state(readField_0, "FileTypeName", "NrrdFile")
set_state(readField_0, "Filename", "%SCIRUNDATADIR%/ToolKits/FwdInvToolbox/pot_based_FEM_forward/Segmentation.nrrd")
set_state(readField_0, "GuiFileTypeName", "")
set_state(readField_0, "ProgrammableInputPortEnabled", False)
set_state(readField_0, "ScriptEnvironmentVariable", "")

# RescaleColorMap:0
set_state(rescaleColorMap_0, "AutoScale", 0)
set_state(rescaleColorMap_0, "FixedMax", 7.824592188084711e-05)
set_state(rescaleColorMap_0, "FixedMin", -0.00010742045437950859)
set_state(rescaleColorMap_0, "ProgrammableInputPortEnabled", False)
set_state(rescaleColorMap_0, "Symmetric", False)

# RescaleColorMap:1
set_state(rescaleColorMap_1, "AutoScale", 0)
set_state(rescaleColorMap_1, "FixedMax", 0.026243155018578514)
set_state(rescaleColorMap_1, "FixedMin", 9.780943031088306e-09)
set_state(rescaleColorMap_1, "ProgrammableInputPortEnabled", False)
set_state(rescaleColorMap_1, "Symmetric", False)

# SetFieldData:0
set_state(setFieldData_0, "ProgrammableInputPortEnabled", False)
set_state(setFieldData_0, "keepTypeCheckBox", False)

# ShowField:0
set_state(showField_0, "CullBackfacingText", False)
set_state(showField_0, "CylinderRadius", 0.1)
set_state(showField_0, "CylinderResolution", 5)
set_state(showField_0, "DefaultMeshColor", "Color(0.5,0.5,0.5)")
set_state(showField_0, "DefaultTextColor", "Color(1,1,1)")
set_state(showField_0, "EdgeTransparency", False)
set_state(showField_0, "EdgeTransparencyValue", 0.6499999761581421)
set_state(showField_0, "EdgesAsCylinders", 0)
set_state(showField_0, "EdgesAvailable", True)
set_state(showField_0, "EdgesColoring", 1)
set_state(showField_0, "FaceInvertNormals", False)
set_state(showField_0, "FaceTransparency", True)
set_state(showField_0, "FaceTransparencyValue", 0.6499999761581421)
set_state(showField_0, "FacesAvailable", True)
set_state(showField_0, "FacesColoring", 1)
set_state(showField_0, "FieldName", "")
set_state(showField_0, "NodeAsSpheres", 0)
set_state(showField_0, "NodeTransparency", False)
set_state(showField_0, "NodeTransparencyValue", 0.6499999761581421)
set_state(showField_0, "NodesAvailable", True)
set_state(showField_0, "NodesColoring", 1)
set_state(showField_0, "ProgrammableInputPortEnabled", False)
set_state(showField_0, "RenderAsLocation", False)
set_state(showField_0, "ShowCellIndices", False)
set_state(showField_0, "ShowDataValues", True)
set_state(showField_0, "ShowEdgeIndices", False)
set_state(showField_0, "ShowEdges", False)
set_state(showField_0, "ShowFaceIndices", False)
set_state(showField_0, "ShowFaces", True)
set_state(showField_0, "ShowNodeIndices", False)
set_state(showField_0, "ShowNodes", False)
set_state(showField_0, "ShowText", False)
set_state(showField_0, "SphereResolution", 5)
set_state(showField_0, "SphereScaleValue", 0.03)
set_state(showField_0, "TextAlwaysVisible", False)
set_state(showField_0, "TextColoring", 0)
set_state(showField_0, "TextPrecision", 3)
set_state(showField_0, "TextSize", 8)
set_state(showField_0, "UseFaceNormals", False)

# ShowField:1
set_state(showField_1, "CullBackfacingText", False)
set_state(showField_1, "CylinderRadius", 0.1)
set_state(showField_1, "CylinderResolution", 5)
set_state(showField_1, "DefaultMeshColor", "Color(0.5,0.5,0.5)")
set_state(showField_1, "DefaultTextColor", "Color(1,1,1)")
set_state(showField_1, "EdgeTransparency", False)
set_state(showField_1, "EdgeTransparencyValue", 0.6499999761581421)
set_state(showField_1, "EdgesAsCylinders", 0)
set_state(showField_1, "EdgesAvailable", True)
set_state(showField_1, "EdgesColoring", 1)
set_state(showField_1, "FaceInvertNormals", False)
set_state(showField_1, "FaceTransparency", False)
set_state(showField_1, "FaceTransparencyValue", 0.6499999761581421)
set_state(showField_1, "FacesAvailable", False)
set_state(showField_1, "FacesColoring", 1)
set_state(showField_1, "FieldName", "")
set_state(showField_1, "NodeAsSpheres", 0)
set_state(showField_1, "NodeTransparency", False)
set_state(showField_1, "NodeTransparencyValue", 0.6499999761581421)
set_state(showField_1, "NodesAvailable", True)
set_state(showField_1, "NodesColoring", 1)
set_state(showField_1, "ProgrammableInputPortEnabled", False)
set_state(showField_1, "RenderAsLocation", False)
set_state(showField_1, "ShowCellIndices", False)
set_state(showField_1, "ShowDataValues", True)
set_state(showField_1, "ShowEdgeIndices", False)
set_state(showField_1, "ShowEdges", True)
set_state(showField_1, "ShowFaceIndices", False)
set_state(showField_1, "ShowFaces", False)
set_state(showField_1, "ShowNodeIndices", False)
set_state(showField_1, "ShowNodes", False)
set_state(showField_1, "ShowText", False)
set_state(showField_1, "SphereResolution", 5)
set_state(showField_1, "SphereScaleValue", 0.03)
set_state(showField_1, "TextAlwaysVisible", False)
set_state(showField_1, "TextColoring", 0)
set_state(showField_1, "TextPrecision", 3)
set_state(showField_1, "TextSize", 8)
set_state(showField_1, "UseFaceNormals", False)

# ShowFieldGlyphs:0
set_state(showFieldGlyphs_0, "ArrowHeadRatio", 0.5)
set_state(showFieldGlyphs_0, "DefaultMeshColor", "Color(0.5,0.5,0.5)")
set_state(showFieldGlyphs_0, "FieldName", "")
set_state(showFieldGlyphs_0, "NormalizeTensors", False)
set_state(showFieldGlyphs_0, "NormalizeVectors", False)
set_state(showFieldGlyphs_0, "ProgrammableInputPortEnabled", False)
set_state(showFieldGlyphs_0, "RenderBases", False)
set_state(showFieldGlyphs_0, "RenderBidirectionaly", False)
set_state(showFieldGlyphs_0, "RenderTensorsBelowThreshold", True)
set_state(showFieldGlyphs_0, "RenderVectorsBelowThreshold", True)
set_state(showFieldGlyphs_0, "ScalarsColoring", 0)
set_state(showFieldGlyphs_0, "ScalarsColoringDataInput", "Primary")
set_state(showFieldGlyphs_0, "ScalarsDisplayType", 0)
set_state(showFieldGlyphs_0, "ScalarsResolution", 10)
set_state(showFieldGlyphs_0, "ScalarsScale", 0.1)
set_state(showFieldGlyphs_0, "ScalarsThreshold", 0.0)
set_state(showFieldGlyphs_0, "ScalarsTransparency", False)
set_state(showFieldGlyphs_0, "ScalarsTransparencyValue", 0.65)
set_state(showFieldGlyphs_0, "ScalarsUniformTransparencyValue", 0.65)
set_state(showFieldGlyphs_0, "SecondaryVectorParameterDataInput", "Primary")
set_state(showFieldGlyphs_0, "SecondaryVectorParameterScale", 0.25)
set_state(showFieldGlyphs_0, "SecondaryVectorParameterScalingType", 1)
set_state(showFieldGlyphs_0, "ShowNormals", False)
set_state(showFieldGlyphs_0, "ShowNormalsScale", 0.1)
set_state(showFieldGlyphs_0, "ShowScalarTab", False)
set_state(showFieldGlyphs_0, "ShowScalars", False)
set_state(showFieldGlyphs_0, "ShowSecondaryTab", False)
set_state(showFieldGlyphs_0, "ShowTensorTab", False)
set_state(showFieldGlyphs_0, "ShowTensors", False)
set_state(showFieldGlyphs_0, "ShowTertiaryTab", False)
set_state(showFieldGlyphs_0, "ShowVectorTab", True)
set_state(showFieldGlyphs_0, "ShowVectors", True)
set_state(showFieldGlyphs_0, "SuperquadricEmphasis", 0.85)
set_state(showFieldGlyphs_0, "TensorsColoring", 0)
set_state(showFieldGlyphs_0, "TensorsColoringDataInput", "Primary")
set_state(showFieldGlyphs_0, "TensorsDisplayType", 2)
set_state(showFieldGlyphs_0, "TensorsResolution", 10)
set_state(showFieldGlyphs_0, "TensorsScale", 0.1)
set_state(showFieldGlyphs_0, "TensorsThreshold", 0.0)
set_state(showFieldGlyphs_0, "TensorsTransparency", False)
set_state(showFieldGlyphs_0, "TensorsTransparencyValue", 0.65)
set_state(showFieldGlyphs_0, "TensorsUniformTransparencyValue", 0.65)
set_state(showFieldGlyphs_0, "VectorsColoring", 1)
set_state(showFieldGlyphs_0, "VectorsColoringDataInput", "Primary")
set_state(showFieldGlyphs_0, "VectorsDisplayType", 4)
set_state(showFieldGlyphs_0, "VectorsResolution", 10)
set_state(showFieldGlyphs_0, "VectorsScale", 10.0)
set_state(showFieldGlyphs_0, "VectorsThreshold", 0.0)
set_state(showFieldGlyphs_0, "VectorsTransparency", False)
set_state(showFieldGlyphs_0, "VectorsTransparencyValue", 0.65)
set_state(showFieldGlyphs_0, "VectorsUniformTransparencyValue", 0.65)

# SolveLinearSystem:0
set_state(solveLinearSystem_0, "MaxIterations", 500.0)
set_state(solveLinearSystem_0, "Method", "cg")
set_state(solveLinearSystem_0, "Preconditioner", "Jacobi")
set_state(solveLinearSystem_0, "ProgrammableInputPortEnabled", False)
set_state(solveLinearSystem_0, "TargetError", 1e-05)

# ViewScene:0
set_state(viewScene_0, "Ambient", 0.2)
set_state(viewScene_0, "AxesSize", 10)
set_state(viewScene_0, "AxesVisible", True)
set_state(viewScene_0, "AxesX", 100)
set_state(viewScene_0, "AxesY", 100)
set_state(viewScene_0, "BackgroundColor", "Color(0,0,0)")
set_state(viewScene_0, "CameraDistance", 3.0)
set_state(viewScene_0, "CameraDistanceMinimum", 1e-10)
set_state(viewScene_0, "CameraLookAt", [0.0, 0.0, 0.0])
set_state(viewScene_0, "CameraRotation", [1.0, 0.0, 0.0, 0.0])
set_state(viewScene_0, "ClippingPlaneD", [0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
set_state(viewScene_0, "ClippingPlaneEnabled", [False, False, False, False, False, False])
set_state(viewScene_0, "ClippingPlaneNormalReversed", [False, False, False, False, False, False])
set_state(viewScene_0, "ClippingPlaneX", [0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
set_state(viewScene_0, "ClippingPlaneY", [0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
set_state(viewScene_0, "ClippingPlaneZ", [0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
set_state(viewScene_0, "Diffuse", 1.0)
set_state(viewScene_0, "Emission", 0.0)
set_state(viewScene_0, "FogColor", "Color(0,0,1)")
set_state(viewScene_0, "FogEnd", 0.71)
set_state(viewScene_0, "FogOn", False)
set_state(viewScene_0, "FogStart", 0.0)
set_state(viewScene_0, "GeometryFeedbackInfo", [107, 244])
set_state(viewScene_0, "HasNewGeometry", False)
set_state(viewScene_0, "HeadLightAzimuth", 180)
set_state(viewScene_0, "HeadLightColor", "Color(1,1,1)")
set_state(viewScene_0, "HeadLightInclination", 90)
set_state(viewScene_0, "HeadLightOn", True)
set_state(viewScene_0, "IsExecuting", False)
set_state(viewScene_0, "IsFloating", True)
set_state(viewScene_0, "Light1Azimuth", 180)
set_state(viewScene_0, "Light1Color", "Color(1,1,1)")
set_state(viewScene_0, "Light1Inclination", 90)
set_state(viewScene_0, "Light1On", False)
set_state(viewScene_0, "Light2Azimuth", 180)
set_state(viewScene_0, "Light2Color", "Color(1,1,1)")
set_state(viewScene_0, "Light2Inclination", 90)
set_state(viewScene_0, "Light2On", False)
set_state(viewScene_0, "Light3Azimuth", 180)
set_state(viewScene_0, "Light3Color", "Color(1,1,1)")
set_state(viewScene_0, "Light3Inclination", 90)
set_state(viewScene_0, "Light3On", False)
set_state(viewScene_0, "ObjectsOnly", True)
set_state(viewScene_0, "ProgrammableInputPortEnabled", False)
set_state(viewScene_0, "ScaleBarFontSize", 8)
set_state(viewScene_0, "ScaleBarHeight", 1.0)
set_state(viewScene_0, "ScaleBarLength", 1.0)
set_state(viewScene_0, "ScaleBarLineColor", 1.0)
set_state(viewScene_0, "ScaleBarLineWidth", 1.0)
set_state(viewScene_0, "ScaleBarMultiplier", 1.0)
set_state(viewScene_0, "ScaleBarNumTicks", 11)
set_state(viewScene_0, "ScaleBarUnitValue", "mm")
set_state(viewScene_0, "ScreenshotDirectory", "")
set_state(viewScene_0, "Shine", 0.5)
set_state(viewScene_0, "ShowScaleBar", False)
set_state(viewScene_0, "ShowViewer", False)
set_state(viewScene_0, "Specular", 0.3)
set_state(viewScene_0, "ToolBarAdvancedPosition", 2)
set_state(viewScene_0, "ToolBarMainPosition", 4)
set_state(viewScene_0, "ToolBarRenderPosition", 1)
set_state(viewScene_0, "UseBGColor", True)
set_state(viewScene_0, "VisibleItemListState", [])
set_state(viewScene_0, "WindowPositionX", 200)
set_state(viewScene_0, "WindowPositionY", 200)
set_state(viewScene_0, "WindowSizeX", 450)
set_state(viewScene_0, "WindowSizeY", 450)

# ViewScene:2
set_state(viewScene_2, "Ambient", 0.2)
set_state(viewScene_2, "AxesSize", 10)
set_state(viewScene_2, "AxesVisible", True)
set_state(viewScene_2, "AxesX", 100)
set_state(viewScene_2, "AxesY", 100)
set_state(viewScene_2, "BackgroundColor", "Color(0,0,0)")
set_state(viewScene_2, "CameraDistance", 3.0)
set_state(viewScene_2, "CameraDistanceMinimum", 1e-10)
set_state(viewScene_2, "CameraLookAt", [0.0, 0.0, 0.0])
set_state(viewScene_2, "CameraRotation", [1.0, 0.0, 0.0, 0.0])
set_state(viewScene_2, "ClippingPlaneD", [0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
set_state(viewScene_2, "ClippingPlaneEnabled", [False, False, False, False, False, False])
set_state(viewScene_2, "ClippingPlaneNormalReversed", [False, False, False, False, False, False])
set_state(viewScene_2, "ClippingPlaneX", [0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
set_state(viewScene_2, "ClippingPlaneY", [0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
set_state(viewScene_2, "ClippingPlaneZ", [0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
set_state(viewScene_2, "Diffuse", 1.0)
set_state(viewScene_2, "Emission", 0.0)
set_state(viewScene_2, "FogColor", "Color(0,0,1)")
set_state(viewScene_2, "FogEnd", 0.71)
set_state(viewScene_2, "FogOn", False)
set_state(viewScene_2, "FogStart", 0.0)
set_state(viewScene_2, "GeometryFeedbackInfo", [262, 155])
set_state(viewScene_2, "HasNewGeometry", False)
set_state(viewScene_2, "HeadLightAzimuth", 180)
set_state(viewScene_2, "HeadLightColor", "Color(1,1,1)")
set_state(viewScene_2, "HeadLightInclination", 90)
set_state(viewScene_2, "HeadLightOn", True)
set_state(viewScene_2, "IsExecuting", False)
set_state(viewScene_2, "IsFloating", True)
set_state(viewScene_2, "Light1Azimuth", 180)
set_state(viewScene_2, "Light1Color", "Color(1,1,1)")
set_state(viewScene_2, "Light1Inclination", 90)
set_state(viewScene_2, "Light1On", False)
set_state(viewScene_2, "Light2Azimuth", 180)
set_state(viewScene_2, "Light2Color", "Color(1,1,1)")
set_state(viewScene_2, "Light2Inclination", 90)
set_state(viewScene_2, "Light2On", False)
set_state(viewScene_2, "Light3Azimuth", 180)
set_state(viewScene_2, "Light3Color", "Color(1,1,1)")
set_state(viewScene_2, "Light3Inclination", 90)
set_state(viewScene_2, "Light3On", False)
set_state(viewScene_2, "ObjectsOnly", True)
set_state(viewScene_2, "ProgrammableInputPortEnabled", False)
set_state(viewScene_2, "ScaleBarFontSize", 8)
set_state(viewScene_2, "ScaleBarHeight", 1.0)
set_state(viewScene_2, "ScaleBarLength", 1.0)
set_state(viewScene_2, "ScaleBarLineColor", 1.0)
set_state(viewScene_2, "ScaleBarLineWidth", 1.0)
set_state(viewScene_2, "ScaleBarMultiplier", 1.0)
set_state(viewScene_2, "ScaleBarNumTicks", 11)
set_state(viewScene_2, "ScaleBarUnitValue", "mm")
set_state(viewScene_2, "ScreenshotDirectory", "")
set_state(viewScene_2, "Shine", 0.5)
set_state(viewScene_2, "ShowScaleBar", False)
set_state(viewScene_2, "ShowViewer", False)
set_state(viewScene_2, "Specular", 0.3)
set_state(viewScene_2, "ToolBarAdvancedPosition", 2)
set_state(viewScene_2, "ToolBarMainPosition", 4)
set_state(viewScene_2, "ToolBarRenderPosition", 1)
set_state(viewScene_2, "UseBGColor", True)
set_state(viewScene_2, "VisibleItemListState", [])
set_state(viewScene_2, "WindowPositionX", 200)
set_state(viewScene_2, "WindowPositionY", 200)
set_state(viewScene_2, "WindowSizeX", 450)
set_state(viewScene_2, "WindowSizeY", 450)

scirun_connect_modules(convertHexVolToTetVol_0, 0, applyFEMCurrentSource_0, 0)
scirun_connect_modules(createFieldData_0, 0, applyFEMCurrentSource_0, 1)
scirun_connect_modules(convertHexVolToTetVol_0, 0, buildFEMatrix_0, 0)
scirun_connect_modules(createMatrix_0, 0, buildFEMatrix_0, 1)
scirun_connect_modules(mapFieldDataOntoElements_0, 0, clipFieldByFunction_0, 0)
scirun_connect_modules(clipFieldByFunction_0, 0, convertHexVolToTetVol_0, 0)
scirun_connect_modules(generateSinglePointProbeFromField_0, 1, createFieldData_0, 0)
scirun_connect_modules(readField_0, 0, createLatVol_0, 0)
scirun_connect_modules(getDomainBoundary_0, 0, createLatVol_1, 0)
scirun_connect_modules(getFieldBoundary_0, 0, fairMesh_0, 0)
scirun_connect_modules(createLatVol_1, 0, generatePointSamplesFromFieldOrWidget_0, 0)
scirun_connect_modules(readField_0, 0, generateSinglePointProbeFromField_0, 0)
scirun_connect_modules(mapFieldDataOntoNodes_0, 0, generateStreamLines_0, 0)
scirun_connect_modules(generatePointSamplesFromFieldOrWidget_0, 1, generateStreamLines_0, 1)
scirun_connect_modules(mapFieldDataOntoElements_0, 0, getDomainBoundary_0, 0)
scirun_connect_modules(setFieldData_0, 0, getFieldBoundary_0, 0)
scirun_connect_modules(readField_0, 0, mapFieldDataOntoElements_0, 0)
scirun_connect_modules(createLatVol_0, 0, mapFieldDataOntoElements_0, 2)
scirun_connect_modules(setFieldData_0, 0, mapFieldDataOntoNodes_0, 0)
scirun_connect_modules(setFieldData_0, 0, mapFieldDataOntoNodes_0, 2)
scirun_connect_modules(setFieldData_0, 0, mapFieldDataOntoNodes_1, 0)
scirun_connect_modules(generateStreamLines_0, 0, mapFieldDataOntoNodes_1, 2)
scirun_connect_modules(createStandardColorMap_0, 0, rescaleColorMap_0, 0)
scirun_connect_modules(getFieldBoundary_0, 0, rescaleColorMap_0, 1)
scirun_connect_modules(createStandardColorMap_1, 0, rescaleColorMap_1, 0)
scirun_connect_modules(mapFieldDataOntoNodes_1, 0, rescaleColorMap_1, 1)
scirun_connect_modules(convertHexVolToTetVol_0, 0, setFieldData_0, 0)
scirun_connect_modules(solveLinearSystem_0, 0, setFieldData_0, 1)
scirun_connect_modules(fairMesh_0, 0, showField_0, 0)
scirun_connect_modules(rescaleColorMap_0, 0, showField_0, 1)
scirun_connect_modules(mapFieldDataOntoNodes_1, 0, showField_1, 0)
scirun_connect_modules(rescaleColorMap_1, 0, showField_1, 1)
scirun_connect_modules(createFieldData_0, 0, showFieldGlyphs_0, 0)
scirun_connect_modules(buildFEMatrix_0, 0, solveLinearSystem_0, 0)
scirun_connect_modules(applyFEMCurrentSource_0, 0, solveLinearSystem_0, 1)
scirun_connect_modules(showField_0, 0, viewScene_0, 0)
scirun_connect_modules(showField_1, 0, viewScene_0, 1)
scirun_connect_modules(generateSinglePointProbeFromField_0, 0, viewScene_0, 2)
scirun_connect_modules(showFieldGlyphs_0, 0, viewScene_0, 3)
scirun_connect_modules(showFieldGlyphs_0, 0, viewScene_2, 0)
scirun_connect_modules(generateSinglePointProbeFromField_0, 0, viewScene_2, 1)

if skipped:
    print("Saved state not applied:\n  " + "\n  ".join(skipped))
