# SCIRun network exported to Python.
# Run it with `scirun -s <this file>`, or paste it into the SCIRun Python console.
# Module IDs are reassigned when the script runs, so modules are referred to by variable.

skipped = []
def set_state(module, key, value):
    # Saved networks can hold keys or value types that this version's modules no longer accept.
    try:
        scirun_set_module_state(module, key, value)
    except (ValueError, RuntimeError) as e:
        skipped.append(f"{module} {key}: {e}")

calculateDistanceToField_0 = scirun_add_module("CalculateDistanceToField")
createLatVol_0 = scirun_add_module("CreateLatVol")
createStandardColorMap_0 = scirun_add_module("CreateStandardColorMap")
extractSimpleIsosurface_0 = scirun_add_module("ExtractIsosurface")
generateSinglePointProbeFromField_0 = scirun_add_module("GenerateSinglePointProbeFromField")
getFieldBoundary_0 = scirun_add_module("GetFieldBoundary")
rescaleColorMap_0 = scirun_add_module("RescaleColorMap")
showField_0 = scirun_add_module("ShowField")
showField_1 = scirun_add_module("ShowField")
viewScene_0 = scirun_add_module("ViewScene")

# CalculateDistanceToField:0
set_state(calculateDistanceToField_0, "BasisType", "same as input")
set_state(calculateDistanceToField_0, "OutputFieldDatatype", "double")
set_state(calculateDistanceToField_0, "ProgrammableInputPortEnabled", False)
set_state(calculateDistanceToField_0, "Truncate", False)
set_state(calculateDistanceToField_0, "TruncateDistance", 1.0)

# CreateLatVol:0
set_state(createLatVol_0, "DataAtLocation", 0)
set_state(createLatVol_0, "ElementSizeNormalized", 0)
set_state(createLatVol_0, "PadPercent", 0.0)
set_state(createLatVol_0, "ProgrammableInputPortEnabled", False)
set_state(createLatVol_0, "XSize", 16)
set_state(createLatVol_0, "YSize", 16)
set_state(createLatVol_0, "ZSize", 16)

# CreateStandardColorMap:0
set_state(createStandardColorMap_0, "AlphaUserPointsVector", [])
set_state(createStandardColorMap_0, "ColorMapInvert", False)
set_state(createStandardColorMap_0, "ColorMapName", "Rainbow")
set_state(createStandardColorMap_0, "ColorMapOption", 0)
set_state(createStandardColorMap_0, "ColorMapResolution", 256)
set_state(createStandardColorMap_0, "ColorMapShift", 0.0)
set_state(createStandardColorMap_0, "CustomColor0", "Color(0.2,0.2,0.2)")
set_state(createStandardColorMap_0, "CustomColor1", "Color(0.8,0.8,0.8)")
set_state(createStandardColorMap_0, "DefaultAlphaValue", 0.5)
set_state(createStandardColorMap_0, "ProgrammableInputPortEnabled", False)

# ExtractSimpleIsosurface:0
set_state(extractSimpleIsosurface_0, "GUIIsoValue", 2.0)
set_state(extractSimpleIsosurface_0, "IsovalueChoice", "Quantity")
set_state(extractSimpleIsosurface_0, "IsovalueListInclusiveExclusive", 0)
set_state(extractSimpleIsosurface_0, "IsovalueListString", "0\n0.57735\n1.1547\n1.73205\n2.3094\n2.88675\n3.4641\n")
set_state(extractSimpleIsosurface_0, "IsovalueQuantityFromField", 1)
set_state(extractSimpleIsosurface_0, "ListOfIsovalues", "")
set_state(extractSimpleIsosurface_0, "ManualMaximumIsovalue", 0.0)
set_state(extractSimpleIsosurface_0, "ManualMinimumIsovalue", 0.0)
set_state(extractSimpleIsosurface_0, "ProgrammableInputPortEnabled", False)
set_state(extractSimpleIsosurface_0, "QuantityOfIsovalues", 7)
set_state(extractSimpleIsosurface_0, "SingleIsoValue", 2.0)

# GenerateSinglePointProbeFromField:0
set_state(generateSinglePointProbeFromField_0, "BBoxSize", 10.0)
set_state(generateSinglePointProbeFromField_0, "FieldElem", 0)
set_state(generateSinglePointProbeFromField_0, "FieldNode", 0)
set_state(generateSinglePointProbeFromField_0, "FieldValue", "0")
set_state(generateSinglePointProbeFromField_0, "MoveMethod", "Location")
set_state(generateSinglePointProbeFromField_0, "ProbeColor", "Color(1,1,1)")
set_state(generateSinglePointProbeFromField_0, "ProbeLabel", "")
set_state(generateSinglePointProbeFromField_0, "ProbeSize", 1.0)
set_state(generateSinglePointProbeFromField_0, "ProgrammableInputPortEnabled", False)
set_state(generateSinglePointProbeFromField_0, "SnapToElement", False)
set_state(generateSinglePointProbeFromField_0, "SnapToNode", False)
set_state(generateSinglePointProbeFromField_0, "UseBBoxSize", False)
set_state(generateSinglePointProbeFromField_0, "XLocation", -1.0)
set_state(generateSinglePointProbeFromField_0, "YLocation", -1.0)
set_state(generateSinglePointProbeFromField_0, "ZLocation", -1.0)

# GetFieldBoundary:0
set_state(getFieldBoundary_0, "ProgrammableInputPortEnabled", False)

# RescaleColorMap:0
set_state(rescaleColorMap_0, "AutoScale", 0)
set_state(rescaleColorMap_0, "FixedMax", 3.4641016151377544)
set_state(rescaleColorMap_0, "FixedMin", 0.0)
set_state(rescaleColorMap_0, "ProgrammableInputPortEnabled", False)
set_state(rescaleColorMap_0, "Symmetric", False)

# ShowField:0
set_state(showField_0, "CullBackfacingText", False)
set_state(showField_0, "CylinderRadius", 0.1)
set_state(showField_0, "CylinderResolution", 5)
set_state(showField_0, "DefaultMeshColor", "Color(0.5,0.5,0.5)")
set_state(showField_0, "DefaultTextColor", "Color(1,1,1)")
set_state(showField_0, "EdgeTransparency", False)
set_state(showField_0, "EdgeTransparencyValue", 0.6499999761581421)
set_state(showField_0, "EdgesAsCylinders", 0)
set_state(showField_0, "EdgesAvailable", True)
set_state(showField_0, "EdgesColoring", 1)
set_state(showField_0, "FaceInvertNormals", False)
set_state(showField_0, "FaceTransparency", False)
set_state(showField_0, "FaceTransparencyValue", 0.6499999761581421)
set_state(showField_0, "FacesAvailable", True)
set_state(showField_0, "FacesColoring", 1)
set_state(showField_0, "FieldName", "")
set_state(showField_0, "NodeAsSpheres", 0)
set_state(showField_0, "NodeTransparency", False)
set_state(showField_0, "NodeTransparencyValue", 0.6499999761581421)
set_state(showField_0, "NodesAvailable", True)
set_state(showField_0, "NodesColoring", 1)
set_state(showField_0, "ProgrammableInputPortEnabled", False)
set_state(showField_0, "RenderAsLocation", False)
set_state(showField_0, "ShowCellIndices", False)
set_state(showField_0, "ShowDataValues", True)
set_state(showField_0, "ShowEdgeIndices", False)
set_state(showField_0, "ShowEdges", True)
set_state(showField_0, "ShowFaceIndices", False)
set_state(showField_0, "ShowFaces", True)
set_state(showField_0, "ShowNodeIndices", False)
set_state(showField_0, "ShowNodes", False)
set_state(showField_0, "ShowText", False)
set_state(showField_0, "SphereResolution", 5)
set_state(showField_0, "SphereScaleValue", 0.03)
set_state(showField_0, "TextAlwaysVisible", False)
set_state(showField_0, "TextColoring", 0)
set_state(showField_0, "TextPrecision", 3)
set_state(showField_0, "TextSize", 8)
set_state(showField_0, "UseFaceNormals", False)

# ShowField:1
set_state(showField_1, "CullBackfacingText", False)
set_state(showField_1, "CylinderRadius", 0.1)
set_state(showField_1, "CylinderResolution", 5)
set_state(showField_1, "DefaultMeshColor", "Color(0.5,0.5,0.5)")
set_state(showField_1, "DefaultTextColor", "Color(1,1,1)")
set_state(showField_1, "EdgeTransparency", False)
set_state(showField_1, "EdgeTransparencyValue", 0.6499999761581421)
set_state(showField_1, "EdgesAsCylinders", 0)
set_state(showField_1, "EdgesAvailable", True)
set_state(showField_1, "EdgesColoring", 1)
set_state(showField_1, "FaceInvertNormals", False)
set_state(showField_1, "FaceTransparency", True)
set_state(showField_1, "FaceTransparencyValue", 0.6499999761581421)
set_state(showField_1, "FacesAvailable", True)
set_state(showField_1, "FacesColoring", 1)
set_state(showField_1, "FieldName", "")
set_state(showField_1, "NodeAsSpheres", 0)
set_state(showField_1, "NodeTransparency", False)
set_state(showField_1, "NodeTransparencyValue", 0.6499999761581421)
set_state(showField_1, "NodesAvailable", True)
set_state(showField_1, "NodesColoring", 1)
set_state(showField_1, "ProgrammableInputPortEnabled", False)
set_state(showField_1, "RenderAsLocation", False)
set_state(showField_1, "ShowCellIndices", False)
set_state(showField_1, "ShowDataValues", True)
set_state(showField_1, "ShowEdgeIndices", False)
set_state(showField_1, "ShowEdges", True)
set_state(showField_1, "ShowFaceIndices", False)
set_state(showField_1, "ShowFaces", True)
set_state(showField_1, "ShowNodeIndices", False)
set_state(showField_1, "ShowNodes", False)
set_state(showField_1, "ShowText", False)
set_state(showField_1, "SphereResolution", 5)
set_state(showField_1, "SphereScaleValue", 0.03)
set_state(showField_1, "TextAlwaysVisible", False)
set_state(showField_1, "TextColoring", 0)
set_state(showField_1, "TextPrecision", 3)
set_state(showField_1, "TextSize", 8)
set_state(showField_1, "UseFaceNormals", False)

# ViewScene:0
set_state(viewScene_0, "Ambient", 0.2)
set_state(viewScene_0, "AxesSize", 10)
set_state(viewScene_0, "AxesVisible", True)
set_state(viewScene_0, "AxesX", 100)
set_state(viewScene_0, "AxesY", 100)
set_state(viewScene_0, "BackgroundColor", "Color(0,0,0)")
set_state(viewScene_0, "CameraDistance", 3.0)
set_state(viewScene_0, "CameraDistanceMinimum", 1e-10)
set_state(viewScene_0, "CameraLookAt", [0.0, 0.0, 0.0])
set_state(viewScene_0, "CameraRotation", [1.0, 0.0, 0.0, 0.0])
set_state(viewScene_0, "ClippingPlaneD", [0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
set_state(viewScene_0, "ClippingPlaneEnabled", [False, False, False, False, False, False])
set_state(viewScene_0, "ClippingPlaneNormalReversed", [False, False, False, False, False, False])
set_state(viewScene_0, "ClippingPlaneX", [0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
set_state(viewScene_0, "ClippingPlaneY", [0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
set_state(viewScene_0, "ClippingPlaneZ", [0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
set_state(viewScene_0, "Diffuse", 1.0)
set_state(viewScene_0, "Emission", 0.0)
set_state(viewScene_0, "FogColor", "Color(0,0,1)")
set_state(viewScene_0, "FogEnd", 0.71)
set_state(viewScene_0, "FogOn", False)
set_state(viewScene_0, "FogStart", 0.0)
set_state(viewScene_0, "GeometryFeedbackInfo", [110, 233])
set_state(viewScene_0, "HasNewGeometry", False)
set_state(viewScene_0, "HeadLightAzimuth", 180)
set_state(viewScene_0, "HeadLightColor", "Color(1,1,1)")
set_state(viewScene_0, "HeadLightInclination", 90)
set_state(viewScene_0, "HeadLightOn", True)
set_state(viewScene_0, "IsExecuting", False)
set_state(viewScene_0, "IsFloating", True)
set_state(viewScene_0, "Light1Azimuth", 180)
set_state(viewScene_0, "Light1Color", "Color(1,1,1)")
set_state(viewScene_0, "Light1Inclination", 90)
set_state(viewScene_0, "Light1On", False)
set_state(viewScene_0, "Light2Azimuth", 180)
set_state(viewScene_0, "Light2Color", "Color(1,1,1)")
set_state(viewScene_0, "Light2Inclination", 90)
set_state(viewScene_0, "Light2On", False)
set_state(viewScene_0, "Light3Azimuth", 180)
set_state(viewScene_0, "Light3Color", "Color(1,1,1)")
set_state(viewScene_0, "Light3Inclination", 90)
set_state(viewScene_0, "Light3On", False)
set_state(viewScene_0, "ObjectsOnly", True)
set_state(viewScene_0, "ProgrammableInputPortEnabled", False)
set_state(viewScene_0, "ScaleBarFontSize", 8)
set_state(viewScene_0, "ScaleBarHeight", 1.0)
set_state(viewScene_0, "ScaleBarLength", 1.0)
set_state(viewScene_0, "ScaleBarLineColor", 1.0)
set_state(viewScene_0, "ScaleBarLineWidth", 1.0)
set_state(viewScene_0, "ScaleBarMultiplier", 1.0)
set_state(viewScene_0, "ScaleBarNumTicks", 11)
set_state(viewScene_0, "ScaleBarUnitValue", "mm")
set_state(viewScene_0, "ScreenshotDirectory", "")
set_state(viewScene_0, "Shine", 0.5)
set_state(viewScene_0, "ShowScaleBar", False)
set_state(viewScene_0, "ShowViewer", False)
set_state(viewScene_0, "Specular", 0.3)
set_state(viewScene_0, "ToolBarAdvancedPosition", 2)
set_state(viewScene_0, "ToolBarMainPosition", 4)
set_state(viewScene_0, "ToolBarRenderPosition", 1)
set_state(viewScene_0, "UseBGColor", True)
set_state(viewScene_0, "VisibleItemListState", [])
set_state(viewScene_0, "WindowPositionX", 200)
set_state(viewScene_0, "WindowPositionY", 200)
set_state(viewScene_0, "WindowSizeX", 450)
set_state(viewScene_0, "WindowSizeY", 450)

scirun_connect_modules(createLatVol_0, 0, calculateDistanceToField_0, 0)
scirun_connect_modules(generateSinglePointProbeFromField_0, 1, calculateDistanceToField_0, 1)
scirun_connect_modules(calculateDistanceToField_0, 0, extractSimpleIsosurface_0, 0)
scirun_connect_modules(createLatVol_0, 0, generateSinglePointProbeFromField_0, 0)
scirun_connect_modules(createLatVol_0, 0, getFieldBoundary_0, 0)
scirun_connect_modules(createStandardColorMap_0, 0, rescaleColorMap_0, 0)
scirun_connect_modules(calculateDistanceToField_0, 0, rescaleColorMap_0, 1)
scirun_connect_modules(extractSimpleIsosurface_0, 0, showField_0, 0)
scirun_connect_modules(rescaleColorMap_0, 0, showField_0, 1)
scirun_connect_modules(getFieldBoundary_0, 0, showField_1, 0)
scirun_connect_modules(showField_0, 0, viewScene_0, 0)
scirun_connect_modules(showField_1, 0, viewScene_0, 1)
scirun_connect_modules(generateSinglePointProbeFromField_0, 0, viewScene_0, 2)

if skipped:
    print("Saved state not applied:\n  " + "\n  ".join(skipped))
