# SCIRun network exported to Python.
# Run it with `scirun -s <this file>`, or paste it into the SCIRun Python console.
# Module IDs are reassigned when the script runs, so modules are referred to by variable.

skipped = []
def set_state(module, key, value):
    # Saved networks can hold keys or value types that this version's modules no longer accept.
    try:
        scirun_set_module_state(module, key, value)
    except (ValueError, RuntimeError) as e:
        skipped.append(f"{module} {key}: {e}")

createLatVol_0 = scirun_add_module("CreateLatVol")
createStandardColorMap_0 = scirun_add_module("CreateStandardColorMap")
editMeshBoundingBox_0 = scirun_add_module("EditMeshBoundingBox")
fairMesh_0 = scirun_add_module("FairMesh")
fairMesh_1 = scirun_add_module("FairMesh")
generatePointSamplesFromFieldOrWidget_0 = scirun_add_module("GeneratePointSamplesFromFieldOrWidget")
generateStreamLines_0 = scirun_add_module("GenerateStreamLines")
getFieldBoundary_0 = scirun_add_module("GetFieldBoundary")
getFieldsFromBundle_0 = scirun_add_module("GetFieldsFromBundle")
mapFieldDataOntoNodes_0 = scirun_add_module("MapFieldDataOntoNodes")
readBundle_0 = scirun_add_module("ReadBundle")
rescaleColorMap_0 = scirun_add_module("RescaleColorMap")
rescaleColorMap_1 = scirun_add_module("RescaleColorMap")
showField_0 = scirun_add_module("ShowField")
showField_1 = scirun_add_module("ShowField")
showField_2 = scirun_add_module("ShowField")
showField_3 = scirun_add_module("ShowField")
showField_4 = scirun_add_module("ShowField")
viewScene_1 = scirun_add_module("ViewScene")

# CreateLatVol:0
set_state(createLatVol_0, "DataAtLocation", 0)
set_state(createLatVol_0, "ElementSizeNormalized", 0)
set_state(createLatVol_0, "PadPercent", 0.0)
set_state(createLatVol_0, "ProgrammableInputPortEnabled", False)
set_state(createLatVol_0, "XSize", 16)
set_state(createLatVol_0, "YSize", 16)
set_state(createLatVol_0, "ZSize", 16)

# CreateStandardColorMap:0
set_state(createStandardColorMap_0, "AlphaUserPointsVector", [])
set_state(createStandardColorMap_0, "ColorMapInvert", False)
set_state(createStandardColorMap_0, "ColorMapName", "Rainbow")
set_state(createStandardColorMap_0, "ColorMapOption", 0)
set_state(createStandardColorMap_0, "ColorMapResolution", 256)
set_state(createStandardColorMap_0, "ColorMapShift", 0.0)
set_state(createStandardColorMap_0, "CustomColor0", "Color(0.2,0.2,0.2)")
set_state(createStandardColorMap_0, "CustomColor1", "Color(0.8,0.8,0.8)")
set_state(createStandardColorMap_0, "DefaultAlphaValue", 0.5)
set_state(createStandardColorMap_0, "ProgrammableInputPortEnabled", False)

# EditMeshBoundingBox:0
set_state(editMeshBoundingBox_0, "BoxMode", 0)
set_state(editMeshBoundingBox_0, "BoxRealScale", 0.0)
set_state(editMeshBoundingBox_0, "DataSaved", False)
set_state(editMeshBoundingBox_0, "InputCenterX", "  0.0406")
set_state(editMeshBoundingBox_0, "InputCenterY", "  0.0051")
set_state(editMeshBoundingBox_0, "InputCenterZ", "  0.0444")
set_state(editMeshBoundingBox_0, "InputSizeX", "  0.1344")
set_state(editMeshBoundingBox_0, "InputSizeY", "  0.0990")
set_state(editMeshBoundingBox_0, "InputSizeZ", "  0.1338")
set_state(editMeshBoundingBox_0, "InverseFieldTransformMatrix", [])
set_state(editMeshBoundingBox_0, "NoTranslation", True)
set_state(editMeshBoundingBox_0, "OldScale", 1.0)
set_state(editMeshBoundingBox_0, "OutputCenterX", 0.04061160600000001)
set_state(editMeshBoundingBox_0, "OutputCenterY", 0.005135034000000024)
set_state(editMeshBoundingBox_0, "OutputCenterZ", 0.044375)
set_state(editMeshBoundingBox_0, "OutputSizeX", 0.134437536)
set_state(editMeshBoundingBox_0, "OutputSizeY", 0.09896096400000001)
set_state(editMeshBoundingBox_0, "OutputSizeZ", 0.13375000000000004)
set_state(editMeshBoundingBox_0, "ProgrammableInputPortEnabled", False)
set_state(editMeshBoundingBox_0, "RDITranslation", False)
set_state(editMeshBoundingBox_0, "ResetToInput", True)
set_state(editMeshBoundingBox_0, "Resetting", False)
set_state(editMeshBoundingBox_0, "RestrictD", False)
set_state(editMeshBoundingBox_0, "RestrictI", False)
set_state(editMeshBoundingBox_0, "RestrictR", False)
set_state(editMeshBoundingBox_0, "RestrictX", False)
set_state(editMeshBoundingBox_0, "RestrictY", False)
set_state(editMeshBoundingBox_0, "RestrictZ", False)
set_state(editMeshBoundingBox_0, "RotationTransformMatrix", [])
set_state(editMeshBoundingBox_0, "Scale", 0.1)
set_state(editMeshBoundingBox_0, "ScaleChanged", False)
set_state(editMeshBoundingBox_0, "ScaleTransformMatrix", [])
set_state(editMeshBoundingBox_0, "SetOutputCenter", False)
set_state(editMeshBoundingBox_0, "TranslationPoint", [])
set_state(editMeshBoundingBox_0, "UseOutputCenter", False)
set_state(editMeshBoundingBox_0, "UseOutputSize", False)
set_state(editMeshBoundingBox_0, "XYZTranslation", False)

# FairMesh:0
set_state(fairMesh_0, "FairMeshMethod", "fast")
set_state(fairMesh_0, "FilterCutoff", 0.1)
set_state(fairMesh_0, "Lambda", 0.6307)
set_state(fairMesh_0, "NumIterations", 50)
set_state(fairMesh_0, "ProgrammableInputPortEnabled", False)

# FairMesh:1
set_state(fairMesh_1, "FairMeshMethod", "fast")
set_state(fairMesh_1, "FilterCutoff", 0.1)
set_state(fairMesh_1, "Lambda", 0.6307)
set_state(fairMesh_1, "NumIterations", 50)
set_state(fairMesh_1, "ProgrammableInputPortEnabled", False)

# GeneratePointSamplesFromFieldOrWidget:0
set_state(generatePointSamplesFromFieldOrWidget_0, "ClampToNodes", True)
set_state(generatePointSamplesFromFieldOrWidget_0, "DistributionType", "uniuni")
set_state(generatePointSamplesFromFieldOrWidget_0, "IncrementRNGSeed", True)
set_state(generatePointSamplesFromFieldOrWidget_0, "NumSamples", 50)
set_state(generatePointSamplesFromFieldOrWidget_0, "ProgrammableInputPortEnabled", False)
set_state(generatePointSamplesFromFieldOrWidget_0, "RNGSeed", 3)

# GenerateStreamLines:0
set_state(generateStreamLines_0, "AutoParameters", False)
set_state(generateStreamLines_0, "ProgrammableInputPortEnabled", False)
set_state(generateStreamLines_0, "RemoveColinearPoints", False)
set_state(generateStreamLines_0, "StreamlineDirection", "Both")
set_state(generateStreamLines_0, "StreamlineMaxSteps", 2000)
set_state(generateStreamLines_0, "StreamlineMethod", "RungeKuttaFehlberg")
set_state(generateStreamLines_0, "StreamlineStepSize", 0.01)
set_state(generateStreamLines_0, "StreamlineTolerance", 0.0001)
set_state(generateStreamLines_0, "StreamlineValue", "Seed index")
set_state(generateStreamLines_0, "UseMultithreading", True)

# GetFieldBoundary:0
set_state(getFieldBoundary_0, "ProgrammableInputPortEnabled", False)

# GetFieldsFromBundle:0
set_state(getFieldsFromBundle_0, "ProgrammableInputPortEnabled", False)
set_state(getFieldsFromBundle_0, "field1-name", "POTENTIAL_FIELD")
set_state(getFieldsFromBundle_0, "field2-name", "CURRENT_VECTOR_FIELD")
set_state(getFieldsFromBundle_0, "field3-name", "CAN_ELECTRODE")
set_state(getFieldsFromBundle_0, "field4-name", "RED_WIRE_ELECTRODE")
set_state(getFieldsFromBundle_0, "field5-name", "CARDIAC_SURFACE")
set_state(getFieldsFromBundle_0, "field6-name", "field5")

# MapFieldDataOntoNodes:0
set_state(mapFieldDataOntoNodes_0, "InterpolationModel", "interpolateddata")
set_state(mapFieldDataOntoNodes_0, "MaxDistance", 1.7976931348623157e+308)
set_state(mapFieldDataOntoNodes_0, "OutsideValue", 0.0)
set_state(mapFieldDataOntoNodes_0, "ProgrammableInputPortEnabled", False)
set_state(mapFieldDataOntoNodes_0, "Quantity", "value")

# ReadBundle:0
set_state(readBundle_0, "FileTypeName", "SCIRun Bundle File")
set_state(readBundle_0, "Filename", "%SCIRUNDATADIR%/IBBM2015/Defib_simulation_results.bdl")
set_state(readBundle_0, "GuiFileTypeName", "")
set_state(readBundle_0, "ProgrammableInputPortEnabled", False)
set_state(readBundle_0, "ScriptEnvironmentVariable", "")

# RescaleColorMap:0
set_state(rescaleColorMap_0, "AutoScale", 0)
set_state(rescaleColorMap_0, "FixedMax", 499.46815928618474)
set_state(rescaleColorMap_0, "FixedMin", 218.38716451945004)
set_state(rescaleColorMap_0, "ProgrammableInputPortEnabled", False)
set_state(rescaleColorMap_0, "Symmetric", False)

# RescaleColorMap:1
set_state(rescaleColorMap_1, "AutoScale", 0)
set_state(rescaleColorMap_1, "FixedMax", 499.99999999999966)
set_state(rescaleColorMap_1, "FixedMin", 0.0)
set_state(rescaleColorMap_1, "ProgrammableInputPortEnabled", False)
set_state(rescaleColorMap_1, "Symmetric", False)

# ShowField:0
set_state(showField_0, "CullBackfacingText", False)
set_state(showField_0, "CylinderRadius", 0.1)
set_state(showField_0, "CylinderResolution", 5)
set_state(showField_0, "DefaultMeshColor", "Color(0,0,0)")
set_state(showField_0, "DefaultTextColor", "Color(1,1,1)")
set_state(showField_0, "EdgeTransparency", False)
set_state(showField_0, "EdgeTransparencyValue", 0.6499999761581421)
set_state(showField_0, "EdgesAsCylinders", 0)
set_state(showField_0, "EdgesAvailable", True)
set_state(showField_0, "EdgesColoring", 1)
set_state(showField_0, "FaceInvertNormals", False)
set_state(showField_0, "FaceTransparency", False)
set_state(showField_0, "FaceTransparencyValue", 0.6499999761581421)
set_state(showField_0, "FacesAvailable", True)
set_state(showField_0, "FacesColoring", 1)
set_state(showField_0, "FieldName", "")
set_state(showField_0, "NodeAsSpheres", 0)
set_state(showField_0, "NodeTransparency", False)
set_state(showField_0, "NodeTransparencyValue", 0.6499999761581421)
set_state(showField_0, "NodesAvailable", True)
set_state(showField_0, "NodesColoring", 1)
set_state(showField_0, "ProgrammableInputPortEnabled", False)
set_state(showField_0, "RenderAsLocation", False)
set_state(showField_0, "ShowCellIndices", False)
set_state(showField_0, "ShowDataValues", True)
set_state(showField_0, "ShowEdgeIndices", False)
set_state(showField_0, "ShowEdges", False)
set_state(showField_0, "ShowFaceIndices", False)
set_state(showField_0, "ShowFaces", True)
set_state(showField_0, "ShowNodeIndices", False)
set_state(showField_0, "ShowNodes", False)
set_state(showField_0, "ShowText", False)
set_state(showField_0, "SphereResolution", 5)
set_state(showField_0, "SphereScaleValue", 0.03)
set_state(showField_0, "TextAlwaysVisible", False)
set_state(showField_0, "TextColoring", 0)
set_state(showField_0, "TextPrecision", 3)
set_state(showField_0, "TextSize", 8)
set_state(showField_0, "UseFaceNormals", False)

# ShowField:1
set_state(showField_1, "CullBackfacingText", False)
set_state(showField_1, "CylinderRadius", 0.1)
set_state(showField_1, "CylinderResolution", 5)
set_state(showField_1, "DefaultMeshColor", "Color(0,0,0)")
set_state(showField_1, "DefaultTextColor", "Color(1,1,1)")
set_state(showField_1, "EdgeTransparency", False)
set_state(showField_1, "EdgeTransparencyValue", 0.6499999761581421)
set_state(showField_1, "EdgesAsCylinders", 0)
set_state(showField_1, "EdgesAvailable", True)
set_state(showField_1, "EdgesColoring", 1)
set_state(showField_1, "FaceInvertNormals", False)
set_state(showField_1, "FaceTransparency", False)
set_state(showField_1, "FaceTransparencyValue", 0.6499999761581421)
set_state(showField_1, "FacesAvailable", True)
set_state(showField_1, "FacesColoring", 1)
set_state(showField_1, "FieldName", "")
set_state(showField_1, "NodeAsSpheres", 0)
set_state(showField_1, "NodeTransparency", False)
set_state(showField_1, "NodeTransparencyValue", 0.6499999761581421)
set_state(showField_1, "NodesAvailable", True)
set_state(showField_1, "NodesColoring", 1)
set_state(showField_1, "ProgrammableInputPortEnabled", False)
set_state(showField_1, "RenderAsLocation", False)
set_state(showField_1, "ShowCellIndices", False)
set_state(showField_1, "ShowDataValues", True)
set_state(showField_1, "ShowEdgeIndices", False)
set_state(showField_1, "ShowEdges", False)
set_state(showField_1, "ShowFaceIndices", False)
set_state(showField_1, "ShowFaces", True)
set_state(showField_1, "ShowNodeIndices", False)
set_state(showField_1, "ShowNodes", False)
set_state(showField_1, "ShowText", False)
set_state(showField_1, "SphereResolution", 5)
set_state(showField_1, "SphereScaleValue", 0.03)
set_state(showField_1, "TextAlwaysVisible", False)
set_state(showField_1, "TextColoring", 0)
set_state(showField_1, "TextPrecision", 3)
set_state(showField_1, "TextSize", 8)
set_state(showField_1, "UseFaceNormals", False)

# ShowField:2
set_state(showField_2, "CullBackfacingText", False)
set_state(showField_2, "CylinderRadius", 0.1)
set_state(showField_2, "CylinderResolution", 5)
set_state(showField_2, "DefaultMeshColor", "Color(0.5,0.5,0.5)")
set_state(showField_2, "DefaultTextColor", "Color(1,1,1)")
set_state(showField_2, "EdgeTransparency", False)
set_state(showField_2, "EdgeTransparencyValue", 0.6499999761581421)
set_state(showField_2, "EdgesAsCylinders", 0)
set_state(showField_2, "EdgesAvailable", True)
set_state(showField_2, "EdgesColoring", 1)
set_state(showField_2, "FaceInvertNormals", False)
set_state(showField_2, "FaceTransparency", False)
set_state(showField_2, "FaceTransparencyValue", 0.6499999761581421)
set_state(showField_2, "FacesAvailable", False)
set_state(showField_2, "FacesColoring", 1)
set_state(showField_2, "FieldName", "")
set_state(showField_2, "NodeAsSpheres", 0)
set_state(showField_2, "NodeTransparency", False)
set_state(showField_2, "NodeTransparencyValue", 0.6499999761581421)
set_state(showField_2, "NodesAvailable", True)
set_state(showField_2, "NodesColoring", 1)
set_state(showField_2, "ProgrammableInputPortEnabled", False)
set_state(showField_2, "RenderAsLocation", False)
set_state(showField_2, "ShowCellIndices", False)
set_state(showField_2, "ShowDataValues", True)
set_state(showField_2, "ShowEdgeIndices", False)
set_state(showField_2, "ShowEdges", True)
set_state(showField_2, "ShowFaceIndices", False)
set_state(showField_2, "ShowFaces", False)
set_state(showField_2, "ShowNodeIndices", False)
set_state(showField_2, "ShowNodes", False)
set_state(showField_2, "ShowText", False)
set_state(showField_2, "SphereResolution", 5)
set_state(showField_2, "SphereScaleValue", 0.03)
set_state(showField_2, "TextAlwaysVisible", False)
set_state(showField_2, "TextColoring", 0)
set_state(showField_2, "TextPrecision", 3)
set_state(showField_2, "TextSize", 8)
set_state(showField_2, "UseFaceNormals", False)

# ShowField:3
set_state(showField_3, "CullBackfacingText", False)
set_state(showField_3, "CylinderRadius", 0.1)
set_state(showField_3, "CylinderResolution", 5)
set_state(showField_3, "DefaultMeshColor", "Color(0.5,0.5,0.5)")
set_state(showField_3, "DefaultTextColor", "Color(1,1,1)")
set_state(showField_3, "EdgeTransparency", False)
set_state(showField_3, "EdgeTransparencyValue", 0.6499999761581421)
set_state(showField_3, "EdgesAsCylinders", 0)
set_state(showField_3, "EdgesAvailable", True)
set_state(showField_3, "EdgesColoring", 1)
set_state(showField_3, "FaceInvertNormals", False)
set_state(showField_3, "FaceTransparency", True)
set_state(showField_3, "FaceTransparencyValue", 0.4)
set_state(showField_3, "FacesAvailable", True)
set_state(showField_3, "FacesColoring", 1)
set_state(showField_3, "FieldName", "")
set_state(showField_3, "NodeAsSpheres", 0)
set_state(showField_3, "NodeTransparency", False)
set_state(showField_3, "NodeTransparencyValue", 0.6499999761581421)
set_state(showField_3, "NodesAvailable", True)
set_state(showField_3, "NodesColoring", 1)
set_state(showField_3, "ProgrammableInputPortEnabled", False)
set_state(showField_3, "RenderAsLocation", False)
set_state(showField_3, "ShowCellIndices", False)
set_state(showField_3, "ShowDataValues", True)
set_state(showField_3, "ShowEdgeIndices", False)
set_state(showField_3, "ShowEdges", False)
set_state(showField_3, "ShowFaceIndices", False)
set_state(showField_3, "ShowFaces", True)
set_state(showField_3, "ShowNodeIndices", False)
set_state(showField_3, "ShowNodes", False)
set_state(showField_3, "ShowText", False)
set_state(showField_3, "SphereResolution", 5)
set_state(showField_3, "SphereScaleValue", 0.03)
set_state(showField_3, "TextAlwaysVisible", False)
set_state(showField_3, "TextColoring", 0)
set_state(showField_3, "TextPrecision", 3)
set_state(showField_3, "TextSize", 8)
set_state(showField_3, "UseFaceNormals", False)

# ShowField:4
set_state(showField_4, "CullBackfacingText", False)
set_state(showField_4, "CylinderRadius", 0.1)
set_state(showField_4, "CylinderResolution", 5)
set_state(showField_4, "DefaultMeshColor", "Color(0.498039,0.283253,0.298558)")
set_state(showField_4, "DefaultTextColor", "Color(1,1,1)")
set_state(showField_4, "EdgeTransparency", False)
set_state(showField_4, "EdgeTransparencyValue", 0.6499999761581421)
set_state(showField_4, "EdgesAsCylinders", 0)
set_state(showField_4, "EdgesAvailable", True)
set_state(showField_4, "EdgesColoring", 1)
set_state(showField_4, "FaceInvertNormals", False)
set_state(showField_4, "FaceTransparency", True)
set_state(showField_4, "FaceTransparencyValue", 0.5)
set_state(showField_4, "FacesAvailable", True)
set_state(showField_4, "FacesColoring", 1)
set_state(showField_4, "FieldName", "")
set_state(showField_4, "NodeAsSpheres", 0)
set_state(showField_4, "NodeTransparency", False)
set_state(showField_4, "NodeTransparencyValue", 0.6499999761581421)
set_state(showField_4, "NodesAvailable", True)
set_state(showField_4, "NodesColoring", 1)
set_state(showField_4, "ProgrammableInputPortEnabled", False)
set_state(showField_4, "RenderAsLocation", False)
set_state(showField_4, "ShowCellIndices", False)
set_state(showField_4, "ShowDataValues", True)
set_state(showField_4, "ShowEdgeIndices", False)
set_state(showField_4, "ShowEdges", False)
set_state(showField_4, "ShowFaceIndices", False)
set_state(showField_4, "ShowFaces", True)
set_state(showField_4, "ShowNodeIndices", False)
set_state(showField_4, "ShowNodes", False)
set_state(showField_4, "ShowText", False)
set_state(showField_4, "SphereResolution", 5)
set_state(showField_4, "SphereScaleValue", 0.03)
set_state(showField_4, "TextAlwaysVisible", False)
set_state(showField_4, "TextColoring", 0)
set_state(showField_4, "TextPrecision", 3)
set_state(showField_4, "TextSize", 8)
set_state(showField_4, "UseFaceNormals", False)

# ViewScene:1
set_state(viewScene_1, "Ambient", 0.2)
set_state(viewScene_1, "AxesSize", 10)
set_state(viewScene_1, "AxesVisible", True)
set_state(viewScene_1, "AxesX", 100)
set_state(viewScene_1, "AxesY", 100)
set_state(viewScene_1, "BackgroundColor", "Color(0,0,0)")
set_state(viewScene_1, "CameraDistance", 3.0)
set_state(viewScene_1, "CameraDistanceMinimum", 1e-10)
set_state(viewScene_1, "CameraLookAt", [0.0, 0.0, 0.0])
set_state(viewScene_1, "CameraRotation", [1.0, 0.0, 0.0, 0.0])
set_state(viewScene_1, "ClippingPlaneD", [0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
set_state(viewScene_1, "ClippingPlaneEnabled", [False, False, False, False, False, False])
set_state(viewScene_1, "ClippingPlaneNormalReversed", [False, False, False, False, False, False])
set_state(viewScene_1, "ClippingPlaneX", [0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
set_state(viewScene_1, "ClippingPlaneY", [0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
set_state(viewScene_1, "ClippingPlaneZ", [0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
set_state(viewScene_1, "Diffuse", 1.0)
set_state(viewScene_1, "Emission", 0.0)
set_state(viewScene_1, "FogColor", "Color(0,0,1)")
set_state(viewScene_1, "FogEnd", 0.71)
set_state(viewScene_1, "FogOn", False)
set_state(viewScene_1, "FogStart", 0.0)
set_state(viewScene_1, "GeometryFeedbackInfo", [120, 286])
set_state(viewScene_1, "HasNewGeometry", False)
set_state(viewScene_1, "HeadLightAzimuth", 180)
set_state(viewScene_1, "HeadLightColor", "Color(1,1,1)")
set_state(viewScene_1, "HeadLightInclination", 90)
set_state(viewScene_1, "HeadLightOn", True)
set_state(viewScene_1, "IsExecuting", False)
set_state(viewScene_1, "IsFloating", True)
set_state(viewScene_1, "Light1Azimuth", 180)
set_state(viewScene_1, "Light1Color", "Color(1,1,1)")
set_state(viewScene_1, "Light1Inclination", 90)
set_state(viewScene_1, "Light1On", False)
set_state(viewScene_1, "Light2Azimuth", 180)
set_state(viewScene_1, "Light2Color", "Color(1,1,1)")
set_state(viewScene_1, "Light2Inclination", 90)
set_state(viewScene_1, "Light2On", False)
set_state(viewScene_1, "Light3Azimuth", 180)
set_state(viewScene_1, "Light3Color", "Color(1,1,1)")
set_state(viewScene_1, "Light3Inclination", 90)
set_state(viewScene_1, "Light3On", False)
set_state(viewScene_1, "ObjectsOnly", True)
set_state(viewScene_1, "ProgrammableInputPortEnabled", False)
set_state(viewScene_1, "ScaleBarFontSize", 8)
set_state(viewScene_1, "ScaleBarHeight", 1.0)
set_state(viewScene_1, "ScaleBarLength", 1.0)
set_state(viewScene_1, "ScaleBarLineColor", 1.0)
set_state(viewScene_1, "ScaleBarLineWidth", 1.0)
set_state(viewScene_1, "ScaleBarMultiplier", 1.0)
set_state(viewScene_1, "ScaleBarNumTicks", 11)
set_state(viewScene_1, "ScaleBarUnitValue", "mm")
set_state(viewScene_1, "ScreenshotDirectory", "")
set_state(viewScene_1, "Shine", 0.5)
set_state(viewScene_1, "ShowScaleBar", False)
set_state(viewScene_1, "ShowViewer", False)
set_state(viewScene_1, "Specular", 0.3)
set_state(viewScene_1, "ToolBarAdvancedPosition", 2)
set_state(viewScene_1, "ToolBarMainPosition", 4)
set_state(viewScene_1, "ToolBarRenderPosition", 1)
set_state(viewScene_1, "UseBGColor", True)
set_state(viewScene_1, "VisibleItemListState", [])
set_state(viewScene_1, "WindowPositionX", 200)
set_state(viewScene_1, "WindowPositionY", 200)
set_state(viewScene_1, "WindowSizeX", 450)
set_state(viewScene_1, "WindowSizeY", 450)

scirun_connect_modules(getFieldsFromBundle_0, 5, createLatVol_0, 0)
scirun_connect_modules(createLatVol_0, 0, editMeshBoundingBox_0, 0)
scirun_connect_modules(getFieldsFromBundle_0, 5, fairMesh_0, 0)
scirun_connect_modules(getFieldBoundary_0, 0, fairMesh_1, 0)
scirun_connect_modules(editMeshBoundingBox_0, 0, generatePointSamplesFromFieldOrWidget_0, 0)
scirun_connect_modules(getFieldsFromBundle_0, 2, generateStreamLines_0, 0)
scirun_connect_modules(generatePointSamplesFromFieldOrWidget_0, 1, generateStreamLines_0, 1)
scirun_connect_modules(getFieldsFromBundle_0, 1, getFieldBoundary_0, 0)
scirun_connect_modules(readBundle_0, 0, getFieldsFromBundle_0, 0)
scirun_connect_modules(getFieldsFromBundle_0, 1, mapFieldDataOntoNodes_0, 0)
scirun_connect_modules(generateStreamLines_0, 0, mapFieldDataOntoNodes_0, 2)
scirun_connect_modules(createStandardColorMap_0, 0, rescaleColorMap_0, 0)
scirun_connect_modules(getFieldBoundary_0, 0, rescaleColorMap_0, 1)
scirun_connect_modules(createStandardColorMap_0, 0, rescaleColorMap_1, 0)
scirun_connect_modules(mapFieldDataOntoNodes_0, 0, rescaleColorMap_1, 1)
scirun_connect_modules(getFieldsFromBundle_0, 4, showField_0, 0)
scirun_connect_modules(getFieldsFromBundle_0, 3, showField_1, 0)
scirun_connect_modules(mapFieldDataOntoNodes_0, 0, showField_2, 0)
scirun_connect_modules(rescaleColorMap_1, 0, showField_2, 1)
scirun_connect_modules(fairMesh_1, 0, showField_3, 0)
scirun_connect_modules(rescaleColorMap_0, 0, showField_3, 1)
scirun_connect_modules(fairMesh_0, 0, showField_4, 0)
scirun_connect_modules(showField_3, 0, viewScene_1, 0)
scirun_connect_modules(showField_4, 0, viewScene_1, 1)
scirun_connect_modules(showField_2, 0, viewScene_1, 2)
scirun_connect_modules(showField_0, 0, viewScene_1, 3)
scirun_connect_modules(showField_1, 0, viewScene_1, 4)
scirun_connect_modules(showField_4, 0, viewScene_1, 5)

if skipped:
    print("Saved state not applied:\n  " + "\n  ".join(skipped))
