name: mac-build

on:
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  mac-gui:
    uses: ./.github/workflows/reusable-build.yml
    with:
      runner: macOS-latest
      qt-version: '6.10.2'
      scirun-qt-min-version: '6.3.1'
      variant: gui
      build-with-python: true
      artifact-name: SCIRunMacInstaller

  mac-headless:
    uses: ./.github/workflows/reusable-build.yml
    with:
      runner: macOS-latest
      variant: headless
      build-testing: true

  mac-gui-nonpython:
    uses: ./.github/workflows/reusable-build.yml
    with:
      runner: macOS-latest
      qt-version: '6.10.2'
      scirun-qt-min-version: '6.3.1'
      variant: gui
      build-with-python: false
      artifact-name: SCIRunMacNPInstaller

  mac-gui-ospray:
    if: false
    uses: ./.github/workflows/reusable-build.yml
    with:
      runner: macOS-latest
      qt-version: '6.10.2'
      scirun-qt-min-version: '6.3.1'
      variant: gui
      with-ospray: true
      artifact-name: SCIRunMacOsprayInstaller
