name: regression-tests

on:
  push:
    branches:
      - regression-tests-ci
      - master
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  linux-headless-regression:
    uses: ./.github/workflows/reusable-build.yml
    with:
      runner: ubuntu-latest
      variant: headless
      build-testing: true
      run-unit-tests: true
      run-regression-tests: true
