name: windows-build

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  windows-headless:
    uses: ./.github/workflows/reusable-build.yml
    with:
      runner: windows-2022
      variant: headless
      build-testing: true

  windows-gui-qt5:
    uses: ./.github/workflows/reusable-build.yml
    with:
      runner: windows-2022
      qt-version: '5.15.2'
      variant: gui
      build-with-python: false
      artifact-name: SCIRunWindowsInstaller_qt5

  windows-gui-qt6:
    uses: ./.github/workflows/reusable-build.yml
    with:
      runner: windows-2022
      qt-version: '6.3.*'
      variant: gui
      build-with-python: false
      artifact-name: SCIRunWindowsInstaller_qt6

  windows-gui-python-qt5:
    uses: ./.github/workflows/reusable-build.yml
    with:
      runner: windows-2022
      qt-version: '5.15.2'
      variant: gui
      build-with-python: true
      artifact-name: SCIRunWindowsPythonInstaller_qt5

  windows-gui-python-qt6:
    uses: ./.github/workflows/reusable-build.yml
    with:
      runner: windows-2022
      qt-version: '6.3.*'
      variant: gui
      build-with-python: true
      artifact-name: SCIRunWindowsPythonInstaller_qt6
